documenso/documenso

apps/web/pages/documents/[id]/recipients.tsx
As suggested, this PR adds a user feedback, when any of entered email(s) is invalid. 
|Preview|
|--|
|Entered email is invalid <br> - When user clicks on `Send`, a toast error appears (preventing the dialog from opening) |
|![image](https://user-images.githubusercontent.com/65268462/232339632-077961f2-6f96-4063-8fa1-850a0ff20dd9.png)
Fixes #71
=> Toast error for invalid email

packages/lib/mail/signingRequestTemplate.ts
Currently the signing email displays poorly on small devices with the line wrapping causing the button to look broken.
Resolve this by using whitespace no-wrap.
Closes #46
=> fix: signing email breaks on small devices

apps/web/components/editor/recipient-selector.tsx
Disable draft recipients within the recipient selector when editing the fields for a given document.
Resolves issues with being able to update and modify fields for draft recipients.
Closes #69
=> fix: disable selection for draft recipients

apps/web/pages/login.tsx, apps/web/pages/signup.tsx
fixes #131
I think we should be using [next middleware](https://nextjs.org/docs/advanced-features/middleware) to do all the redirecting. What do you think? Do you want me to try to do that instead?
=> Redirect to /dashboard if auth user tries to access /login or /signup

apps/web/pages/api/documents/[id]/sign.ts, packages/prisma/migrations/20230421134018_doc_214_add_signed_at_field/migration.sql, packages/prisma/schema.prisma
Updates the signing endpoint to only apply changes to the Date field for the current signer. This is made possible through the addition of the `signedAt` column within the database.
Resolves the issue with one signer filling the date for all recipients and also ensures that the date of signing on a document won't always be todays date after each recipient has signed.
Closes #48
=> fix: date field appears for all recipients

apps/web/components/editor/signature-dialog.tsx, apps/web/hooks/use-debounced-value.ts
Debounces the display of the signing canvas to avoid situations where the canvas renders to 2px due to rendering while a transition is being performed.
Video of the change can be found below:
https://www.loom.com/share/69f3f0b6374247098bb61cc4ce789e81
Closes #43
=> fix: debounce display of signing canvas

packages/lib/server/getServerErrorFromUnknown.ts
Fixes #170 
1. imports from "@prisma/client/runtime" are deprecated. Using "@prisma/client/runtime/library" instead
https://github.com/prisma/prisma/discussions/17832#discussioncomment-5051532
3. NotFoundError class is deprecated. This has changed to PrismaClientKnownRequestError in 4.10.x
https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/utils/rejectOnNotFound.ts#L13-L24
=> fix: deprecated type checks and imports from @prisma/client

.env.example
Just noticed some typos while setting up a local copy and thought I'd fix them up real quick.
=> Fix typos in example env

apps/web/src/app/(dashboard)/documents/[id]/loading.tsx, apps/web/src/app/(dashboard)/documents/[id]/page.tsx, apps/web/src/components/(dashboard)/pdf-viewer/pdf-viewer.tsx, apps/web/src/components/forms/edit-document.tsx
Added a `loading.tsx` to `/documents/[id]`
>[**Instant Loading States**](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming#instant-loading-states)
An instant loading state is fallback UI that is shown immediately upon navigation. You can pre-render loading indicators such as skeletons and spinners, or a small but meaningful part of future screens such as a cover photo, title, etc. This helps users understand the app is responding and provides a better user experience.
I styled it so that it would flow seamlessly into the other loading client side loading states provided by `edit-documents.tsx` and `pdf-viewer.tsx`
https://www.loom.com/share/e9ff4de4fb6647ffa1d04986d57cfd38?sid=a5cd2fe2-a7ee-4a58-a1c9-7d31562d120f
The back link on the `/documents/[id]` …
=> improved loading state for /document/id

docker/compose-without-app.yml, package.json
This PR addresses an issue where Docker Compose would throw an error due to the invalid 'name' attribute at the top level of our Docker Compose configuration file. To solve this, the PR makes the following changes:
1. Removes the 'name' attribute from the Docker Compose configuration (docker/compose-without-app.yml).
2. Adds the -p documenso option to our Docker Compose commands in package.json. This sets the project name to "documenso", allowing us to manage resources more easily when running multiple Docker Compose projects.
Related issue: https://github.com/documenso/documenso/issues/210
=> Doc 210 fix docker compose name attribute error

apps/web/pages/documents.tsx
In your current situation, the `flex-row-reverse` property is causing the alignment to be to the right even on smaller screens (2nd screenshot). It should be on the left imo.
Recommended fix - We could use `justify-start` for smaller screens and `justify-end` for bigger screens. So on smaller screens, the items will start from the left side, and on medium and larger screens, they will start from the right side, while maintaining the same order.
=> Fixed alignment of div containing selectboxes in mobile and tablet screens

apps/web/src/app/(dashboard)/dashboard/page.tsx
Wrapped `<CardMetric />` with `<Link>` allowing for a one-click shortcut to filtered /documents page.
https://www.loom.com/share/5dd84e1e268c428aa7e5fab2fe008021?sid=2fa3c4ee-96dc-46be-964d-9feed5e004fa
=> linking card metrics to filtered /documents

README.md
Correct the logo url in readme as it currently points to a repository that doesn't exist.
=> Correct readme logo url

.husky/pre-commit, docker/Dockerfile, lint-staged.config.cjs, package-lock.json, package.json
I didn't noticed an issue for this yet, but I did read the blog post about adding it - so this PR implements husky & lint-staged to ensure all future commits are formatted. There are a few ways of configuring lint-staged, I just took the straightforward approach, happy to change it - if preferred.
Additionally, I modified the Dockerfile to disable husky from being installed. You'll see something along the lines of this in the docker build logs when installing dependencies, indicating its been disabled.
```bash
. prepare$ husky install
. prepare: husky - HUSKY env variable is set to 0, skipping install
. prepare: Done
```
=> Add husky & lint staged

.github/workflows/ci.yml
This creates an continuous integration workflow to ensure future pull requests successfully build. We'll want to update the branches to `main` once the refresh branch is released. 
You'll want to enable Actions in the repository/org settings, if it is disabled. 
Test local repo: https://github.com/nsylke/documenso/actions/runs/5885492640
=> ci: create build workflow

.gitignore
Ignore all intellij/webstorm settings and ignore all of vscode settings except for `settings`, `tasks`, `launch` and `extensions`.
=> chore: ignore intellij editor settings and some of vscode

packages/lib/mail/signingRequestTemplate.ts
=> Fixes Showing ask null from SigningEmail Template

.github/workflows/codeql-analysis.yml
- The build fails for `codeql workflow` as there was a small mistake (Apologies for the same) in the build command
=> fix: fixed build command in codeql workflow

apps/marketing/src/app/robots.ts, apps/marketing/src/app/sitemap.ts
With the latest versions of Next.js we can automatically generate robots & sitemap files. 
In the `robots.txt` we are allowing all paths except for `_next` since those files don't need to be crawled. 
In the `sitemap.xml` we are setting all the pages that have been explicitly created and then automatically pulling all generic and blog posts from contentlayer. The sitemap entries are alphabetized based on the directories inside of `app/`.
=> feat: create robots.txt and sitemap.xml

apps/marketing/package.json, apps/web/package.json
Use the built-in `-p` cli option in next for handling port. This is to support Windows, another option would be to use [`cross-env`](https://www.npmjs.com/package/cross-env).
=> fix: use -p cli option for next dev

apps/web/src/components/forms/password.tsx, apps/web/src/components/forms/signin.tsx, apps/web/src/components/forms/signup.tsx
I adjusted the `minLength` to 6 characters since the password change already had it at 6 characters but the signup/signin had it at 1 character. Lets make it consistent across the platform! 
Additionally, I added the `maxLength` to 72 characters since bcrypt supports up 72 bytes. We're currently doing a silent truncation which isn't ideal. In the future, if people request longer passwords, we could look into prehashing the password using `bcrypt(hmac-sha256(salt, password))` to avoid hash shucking and allow passwords longer than 72 characters. Alternatively, we could look at other algorithms like `scrypt`, `pbkdf2` or even `argon2id`.
**Edit:** Added `autoComplete` based on @adithyaakrishna suggestion. This configures password managers to either autofill with the current password or …
=> feat: set min/max lengths and autocomplete for password

package.json
Maybe this was an oversight, or just opinionated, but with rest of apps and packages having `@documenso/[name]`, it makes sense to keep the root package.json consistent and name it `@documenso/root`.
=> chore: change root package.json name

CONTRIBUTING.md, README.md
This PR fixes a typo in CONTRIBUTING.md
before: 
It should be "Select an issue from here or create a new one"
=> docs: fix typo in CONTRUBUTING.md

apps/web/src/components/forms/profile.tsx
fix `Signature Pad cannot be empty` error while updating the username
=> fix: user name not updatable

apps/web/src/components/(dashboard)/avatar/stack-avatar.tsx, apps/web/src/components/(dashboard)/avatar/stack-avatars-with-tooltip.tsx, apps/web/src/components/(dashboard)/avatar/stack-avatars.tsx, apps/web/src/components/(dashboard)/layout/profile-dropdown.tsx, packages/lib/client-only/recipient-avatar-fallback.ts, packages/lib/client-only/recipient-initials.ts, packages/lib/utils/recipient-formatter.ts
Added a fallback to avatars so that when no name is provided, it will use the first letter of the email if possible.
Examples:
- Recipient John Doe (foo@bar.com) will have the fallback text be 'JD'
- Recipient with no name (foo@bar.com) will have the fallback text be 'F'
=> feat: add avatar email fallback

apps/marketing/src/app/robots.ts
The `_next` is breaking the GSC mobile usability. This resolves it.
Related #290
=> fix: remove disallow property of _next from robots

apps/web/src/app/(signing)/sign/[token]/form.tsx
It appears that there may have been an oversight in the code, as the cancel button did not have any associated action. I have addressed this issue by adding a router.back function to facilitate a return to the home page.
=> fix: cancel button handler

packages/lib/server-only/recipient/set-recipients-for-document.ts
A dumb mistake I left in, resolves #445
=> fix: do not overwrite new names or emails for signers

apps/web/src/app/(signing)/sign/[token]/form.tsx, packages/lib/server-only/document/viewed-document.ts
Disable the cancel button when there are 1 or fewer entries in `window.history`, this enables cancellation to go back when signing a document in the Inbox while disabling it when navigating from an email.
Resolves #446
=> fix: disable cancel button when there is no window history

packages/ui/primitives/document-flow/add-signers.tsx, packages/ui/primitives/document-flow/add-signers.types.ts, packages/ui/primitives/form/form-error-message.tsx
Adds a hack that handles `.root` being populated when using Zod and React Hook Form together. 
Resolves #443
=> fix: add hack for root zod validation with hook form

package.json
The `package.json` has a typo causing `prisma:migrate-dev` not to work
Gives the below error while running `npm run dx`
=> fix: typo in `dx` script

packages/ui/primitives/document-flow/add-fields.tsx
Bug:
https://github.com/documenso/documenso/assets/60930192/1a368f70-ba4b-401d-94ee-e822d2ac58c8
After fix:
=> fix: signature text overflow truncated for longer signature texts

apps/marketing/package.json, apps/marketing/src/components/(marketing)/callout.tsx, apps/marketing/src/components/(marketing)/footer.tsx, apps/marketing/src/components/(marketing)/hero.tsx, apps/marketing/src/components/(marketing)/mobile-navigation.tsx, apps/web/package.json, apps/web/src/app/(signing)/sign/[token]/complete/share-button.tsx, apps/web/src/components/(dashboard)/layout/profile-dropdown.tsx, package-lock.json
fixes #358 
Update footer and mobile navigation icons.
As Lucide Icon is not supporting any brand icons and also twitter new icon, so I've updated it to react-icons.
=> fix: update icons

packages/ui/primitives/document-flow/document-flow-root.tsx
UI Bug
The stepper titles are a little confusing
Changed to use Step of:
Closes #500
=> fix: changed text of stepper

apps/web/src/app/(dashboard)/documents/page.tsx
Fix
The frequency dropdown on focus ring is not fully showing correctly:
Added a tiny bit of padding so the full focus shows:
=> fix: frequency focus ring

apps/web/src/app/(dashboard)/documents/data-table-action-dropdown.tsx, packages/prisma/migrations/20231013012902_add_document_share_link_delete_cascade/migration.sql, packages/prisma/schema.prisma
Currently if a user creates a draft document and shares it, they will not be able to delete it.
The following is the error log when you try:
```
PrismaClientKnownRequestError: 
Invalid `prisma.document.delete()` invocation:
Foreign key constraint failed on the field: `DocumentShareLink_documentId_fkey (index)`
at wn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6730)
at wn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6119)
at wn.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5839)
at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:9763)
at async deleteDraftDocument (/var/task/apps/web/.next/server/pages/api/trpc/[trpc].js:534:12)
at async …
```
=> fix: add cascade delete for share links

apps/web/src/app/(dashboard)/admin/documents/data-table.tsx
Fixed an issue with the user avatar on the 'documents' page in the admin dashboard.
=> fix: user avatar on admin documents table

apps/web/src/app/(dashboard)/admin/documents/data-table.tsx
If the user uploaded a file with a long name, it created a huge horizontal scroll.
The name of the file is now truncated if it's too long. Thus, it doesn't break the UI anymore.
=> fix: truncate long file name in admin dashboard

apps/web/src/app/(unauthenticated)/forgot-password/page.tsx, apps/web/src/app/(unauthenticated)/signin/page.tsx
Forgotten your password is not a correct phrase. So, I changed it to 'forgot' in dev mode.
=> fix: change from forgotten to forgot password

apps/marketing/src/components/(marketing)/footer.tsx, apps/marketing/src/components/(marketing)/header.tsx, apps/marketing/src/components/(marketing)/mobile-navigation.tsx
Change "Open" links to "Open Startup" to reduce confusion about how to open the web app.
Additionally add the OSS Friends link to the footer since it was dropped during some changes.
=> chore: marketing site updates

apps/web/src/app/(dashboard)/documents/_action-items/resend-document.tsx
fixes #666 
I have added changes so that the `Resend` button is disabled for the Recipients of the Document. `Resend` button is visible only for the Document senders.
=> #666 feat: disabled resend button for recipients

apps/web/src/app/(dashboard)/documents/[id]/page.tsx, packages/lib/server-only/user/get-all-users.ts
- removes `await` keyword from promises passed to `Promise.all`
Using `await` inside a `Promise.all` will make the awaited Promise resolve first, and only after that the Promise.all will be called.  This means the promises are run serially. In these two cases, we probably don't want that
=> perf(web, lib): do not await inside promise statements

package.json
This PR introduces a node script for db seed.
(`npm run prisma:seed -w @documenso/prisma` doesn't recognize `.env`.)
=> fix: add a script for db seed with env

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx
Editing documents would previously require scrolling to the bottom of the page to progress to the next step, this change makes it so they behave as per the signing page:
=> fix: edit document sizing

apps/marketing/content/careers.mdx, apps/marketing/src/components/(marketing)/footer.tsx, package-lock.json
Adds the careers page to the marketing site so we may publish open positions in the future once we are hiring again.
=> feat(marketing): add careers page

apps/web/src/app/(dashboard)/settings/billing/create-checkout.action.ts
Currently customers with inactive/expired plans will be shown the BillingPlans component but upon hitting the subscribe button they will be redirected to their portal where they are unable to complete a checkout.
To resolve this we check for expiration of their subscription and use a normal stripe checkout instead.
=> fix(webapp): use checkout for expired plans

apps/marketing/src/components/(marketing)/widget.tsx, apps/marketing/src/components/constants.ts
=> refactor: used constant for steps instead of strings

apps/web/src/components/(dashboard)/common/command-menu.tsx
Issue  - The `Ctrl+K` hotkey in our application is conflicting with the browser's default search hotkey, leading to unintended browser actions.
https://github.com/documenso/documenso/assets/71957674/180b6028-58f7-4cf8-841c-1e13c9d4d355
=> fix: hotkeys was overlapping with the browser hotkeys

apps/web/src/app/(dashboard)/documents/data-table-action-dropdown.tsx, apps/web/src/app/(dashboard)/documents/delete-document-dialog.tsx
- Fixes https://linear.app/documenso/issue/DOC-387/delete-document-dialog-should-mention-the-filename
=> feat: show document title for delete dialog - [DOC-387]

apps/web/src/app/(dashboard)/documents/upload-document.tsx, packages/ui/primitives/document-dropzone.tsx
Update the dropzone so it will display the relevant disabled text based on the reason it is disabled.
=> feat: update disabled dropzone text

apps/web/src/components/(dashboard)/layout/header.tsx, packages/ui/primitives/dialog.tsx, packages/ui/primitives/select.tsx, packages/ui/primitives/toast.tsx
Currently there are various z-index values that are causing:
- Toasts to be placed behind dialog blur background
- Menu being cropped off by header
- Revert `z-[1000]` back to `z-50` for the header (not exactly sure why it was bumped)
- Refactor z-indexes over 9000 to start from 1000
- Ensure z-index of toast is higher than dialog
**Mobile toast is on top**
**Toast is in-front of blurred dialog background**
**Dropdown is no longer being cropped off**
=> fix: resolve conflicting z-index values

packages/ui/primitives/document-flow/add-title.tsx
The issue is fixed. Now the box is no more overlapping
=> fix: fixed the title box overlapping issue

apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx
Fixes #710
When the fields are not filled, the button will have the `outline` variant and it'll say "Fill fields". Clicking on the button takes you to the unfilled field.
Once all fields are filled, the button will be green and it'll say "Complete".
Created the PR to move faster and ship the changes asap.
PR based on these PRs:
- https://github.com/documenso/documenso/pull/739 by @Hiperultimate
- https://github.com/documenso/documenso/pull/729 by @ksushant6566
- https://github.com/documenso/documenso/pull/730 by @ketanMehtaa
Thank you for the work, folks!
=> feat: jump to next field

apps/marketing/content/blog/pre-seed.mdx, apps/marketing/content/blog/shop.mdx, packages/ui/primitives/theme-switcher.tsx
I saw the below minor nitpick in the `them-switcher` component. Fixed it with this PR
=> chore: fix color for light mode icon

packages/ui/primitives/document-flow/field-item.tsx
Fixed the deleting signature block issue on touchscreens, for some reason the `onClick` event isn't working on the touchscreens that's why I've added `onTouchEnd` event to delete the signature block when the user clicks on it.
1. Added an `onTouchEnd` event to the delete button on the signature block.
https://github.com/documenso/documenso/assets/87828904/c952a5ff-3188-4859-852c-617547d4b369
Closes #798
=> fix: fixed the deleting signature block issue on touchscreens

apps/web/src/components/(dashboard)/common/command-menu.tsx
fixed the ctrl+k shortcut which by default browser focuses on omnibox (search bar).
added preventDefault option in useHotkeys function as mentioned in react hotkeys hook docs
closes #829
=> fix: keyboard shortcut ctrl+k fixed

apps/web/src/app/(dashboard)/documents/page.tsx
This PR fixes #782.
It now displays the document count on mobile view.
Screenshot:
=> fix: display the number of documents in mobile view

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx, apps/web/src/app/(dashboard)/documents/[id]/page.tsx, apps/web/src/app/(signing)/sign/[token]/page.tsx, package-lock.json, packages/lib/server-only/document-meta/upsert-document-meta.ts, packages/lib/server-only/document/duplicate-document-by-id.ts, packages/prisma/migrations/20240115031508_add_password_to_document_meta/migration.sql, packages/prisma/schema.prisma, packages/trpc/server/document-router/router.ts, packages/trpc/server/document-router/schema.ts, packages/ui/package.json, packages/ui/primitives/document-password-dialog.tsx, packages/ui/primitives/pdf-viewer.tsx
Current Behaviour - 
Presently, the behavior is quite default, which does not align with the theme. Additionally, the alert box appears to be somewhat stubborn.
https://github.com/documenso/documenso/assets/71957674/d681bef6-7ee3-4f27-b6db-34c6aaec6139
This PR fixes - 
I am overriding the default behavior by adding a password dialog component, which will only appear for password-protected documents.
https://github.com/documenso/documenso/assets/71957674/b1d05968-3c15-4abe-810f-e4186cfd1fcb
=> feat: improve the UX for password protected documents

apps/web/src/components/(dashboard)/common/command-menu.tsx, apps/web/src/components/(dashboard)/layout/verify-email-banner.tsx, packages/ui/primitives/command.tsx
fixes #836 
- Explicit `div` is used instead of `<CommandSeparator/>` , since it failed to render borders for dynamic search results, but only works for initial menu.
(initial menu)
(search results)
=> feat: command group distinction

packages/lib/server-only/document/get-stats.ts
completed/pending status gets incremented once if sender is one of the recipients
fixes #853
=> fix: completed/pending status gets incremented once if sender is one of the recipients

packages/lib/next-auth/auth-options.ts
Currently logging in via Google SSO will still require you to verify your email. This shouldn't happen since going through Google SSO implies you have access to that email.
This change resolves that by setting the `emailVerified` attribute in the database when you access the application via Google SSO.
This also updates the identity provider for users who log in through Google to have it correctly set as `GOOGLE`.
- Logged in via SSO and no email verification was requested
- Logged in via non SSO and email verification was requested
=> fix: auto verify google sso emails

apps/web/src/components/(dashboard)/layout/header.tsx, apps/web/src/components/(dashboard)/layout/profile-dropdown.tsx
This pull request solves the problem where the avatar component within the document list has the same z-index value as the header component, causing the avatar to be above the header. When two elements have the same z-index value, the last one takes priority!
Fixes #870 
1. Increases the value of the header's `z-index` by `10` (the current value is `50`)
=> fix: resolve conflicting z-index values btwn avatar in document list and header

apps/web/src/app/(dashboard)/documents/page.tsx, apps/web/src/components/(dashboard)/period-selector/types.ts, packages/lib/server-only/document/find-documents.ts, packages/lib/server-only/document/get-stats.ts
Currently the count for the documents table tabs do not display the correct values when the period filter is applied.
- Updated `getStats` to support filtering on period
- Tested to see if the documents tab count were being filtered based on the period
=> fix: document count period filter

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx, packages/ui/primitives/document-flow/add-fields.tsx, packages/ui/primitives/document-flow/add-signers.tsx, packages/ui/primitives/document-flow/add-subject.tsx, packages/ui/primitives/document-flow/add-title.tsx, packages/ui/primitives/document-flow/show-field-item.tsx, packages/ui/primitives/document-flow/subject-field-item.tsx
=> fix: show fields on every step while editing documents

packages/lib/server-only/field/set-fields-for-document.ts
Fixed issue where you are prevented from removing fields for a recipient that has multiple fields.
Example:
Recipient has 3 fields, you remove 1 and proceed to next step. In the next step the field reappears as it was not deleted.
=> fix: update field remove logic

apps/web/src/app/(dashboard)/documents/data-table-action-dropdown.tsx, apps/web/src/app/(signing)/sign/[token]/name-field.tsx, packages/lib/server-only/field/set-fields-for-document.ts, packages/lib/server-only/recipient/set-recipients-for-document.ts, packages/ui/primitives/document-flow/add-fields.tsx, packages/ui/primitives/document-flow/add-signers.tsx
Fixed issue where setting a recipient role as CC will prevent any further changes as it is considered as "sent" and "signed".
- Prevent editing document after completed
- Removed CC and Viewers from the field recipient list since they will never be filled
- Minor UI issues
=> fix: recipients with CC role not being editable

packages/trpc/server/document-router/schema.ts, packages/ui/primitives/document-flow/add-subject.types.ts
Currently the document redirect URL feature is preventing documents from being created unless a redirect URL is provided.
During the document edit flow, the redirect URL is hidden in an advanced tab with the value of an empty string, which will always fail the current Zod validation since `optional` requires undefined to pass.
There are multiple ways to fix this, but I think this is the easiest method where we can assume an empty string is valid.
Will require retesting the feature since I'm just assuming an empty string won't break anything downstream for the redirect URL feature.
Pinging @adithyaakrishna to retest the feature.
=> fix: redirect URL preventing document flow

apps/web/src/app/(dashboard)/documents/upload-document.tsx
improved document-dropzone ui for small vertical screens (screens less than 800px vertically)
Although it can still become congested on really small vertical screens, but possibility is really low.
fixes: #840
=> fix: improved document-dropzone ui for small vertical screens

apps/web/src/app/(dashboard)/settings/billing/page.tsx, apps/web/src/components/(teams)/tables/teams-member-page-data-table.tsx, packages/ee/server-only/limits/server.ts, packages/ee/server-only/stripe/get-document-related-prices.ts.ts, packages/ee/server-only/stripe/get-enterprise-plan-prices.ts, packages/ee/server-only/stripe/get-prices-by-plan.ts, packages/ee/server-only/stripe/get-primary-account-plan-prices.ts, packages/ee/server-only/stripe/get-team-related-prices.ts, packages/ee/server-only/stripe/transfer-team-subscription.ts, packages/lib/constants/app.ts, packages/lib/constants/billing.ts, packages/lib/server-only/team/create-team.ts, packages/lib/utils/billing.ts
Add support for enterprise billing plans.
Enterprise billing plans by default get access to everything early adopters do:
- Unlimited teams
- Unlimited documents
They will also get additional features in the future.
Pending webhook updates to support enterprise onboarding.
Rolled back env changes `NEXT_PUBLIC_PROJECT` since it doesn't seem to work.
=> feat: add enterprise billing

apps/marketing/next.config.js, apps/web/next.config.js, docker/buildx.sh, package-lock.json, packages/lib/next-auth/auth-options.ts, packages/lib/package.json, packages/lib/server-only/2fa/disable-2fa.ts, packages/lib/server-only/2fa/setup-2fa.ts, packages/lib/server-only/auth/hash.ts, packages/lib/server-only/user/create-user.ts, packages/lib/server-only/user/reset-password.ts, packages/lib/server-only/user/update-password.ts
Remove `bcrypt` in favor of `@node-rs/bcrypt` which includes precompiled binaries for many platforms reducing the number of tasks to run post `npm install`.
Resolves #986
=> chore: remove bcrypt

apps/marketing/content/blog/removing-server-actions.mdx
Fixing the blog date for https://documenso.com/blog/removing-server-actions
(I assume it was meant to be March 7th)
=> fix: fix blog post date

.env.example, apps/marketing/package.json, apps/web/package.json, docker/README.md, docker/production/compose.yml, docker/testing/compose.yml, package-lock.json
Updates the docker documentation and compose files to include key file related configuration for self hosters. This was missed as the key file environment variables weren't documented in the `.env.example` file which was used for creating the docker documentation.
#1012
- Updated the docker configuration to include key file environment variables
- Updated the .env.example to include key file env vars
- Updated the compose images to use volumes for key files
- I have used the containers with the updated values and confirmed that they work as expected
N/A
=> fix: update docker documentation and include cert env vars

packages/eslint-config/index.cjs, tsconfig.eslint.json
I found out that the problem of slow down is the use of parseOption.project with multiple tsconfig files which increases usage of memory consumption quite a lot.
Here is the reference I found to resolve this issue:
[reference link](https://github.com/typescript-eslint/typescript-eslint/issues/1192)
[Doc link](https://typescript-eslint.io/getting-started/typed-linting/monorepos/)
Based on this reference  I created the solution and tested out locally it does reduce the eslint time.
#1002
=> fix: eslint config file parseOptions.project path is updated

packages/ui/primitives/toast.tsx
As per the requirement on the mobile, the close icon will always be visible 
On the desktop, close icon will be visible on hover.
fixes #965
=> fix: show close icon on notification in mobile

packages/ui/primitives/document-flow/add-signers.tsx
Update the add signer form to disable the signers when required.
I assume the actual issue is that `{...field}` was spreading a disabled prop which was overriding our one.
- Use fieldset to disable inputs
- Manually disable select since fieldset doesn't work for that select for some reason
=> fix: disable edit signer inputs

packages/lib/constants/date-formats.ts
=> fix: use correct date format

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx, apps/web/src/app/(dashboard)/documents/[id]/edit/document-edit-page-view.tsx, apps/web/src/app/(signing)/sign/[token]/date-field.tsx, apps/web/src/app/(signing)/sign/[token]/email-field.tsx, apps/web/src/app/(signing)/sign/[token]/name-field.tsx, apps/web/src/app/(signing)/sign/[token]/signature-field.tsx, apps/web/src/app/(signing)/sign/[token]/text-field.tsx, apps/web/src/components/(dashboard)/common/command-menu.tsx, packages/lib/constants/trpc.ts, packages/lib/server-only/document/get-document-with-details-by-id.ts, packages/lib/server-only/field/set-fields-for-document.ts, packages/lib/server-only/recipient/set-recipients-for-document.ts, packages/prisma/types/document.ts, packages/trpc/client/index.ts, packages/trpc/react/index.tsx, packages/trpc/server/document-router/router.ts, packages/trpc/server/document-router/schema.ts
**Fixes issues with mismatching state between document steps.**
For example, editing a recipient and proceeding to the next step may not display the updated recipient. And going back will display the old recipient instead of the updated values.
**This PR also improves mutation and query speeds by adding logic to bypass query invalidation.**
```ts
export const trpc = createTRPCReact<AppRouter>({
unstable_overrides: {
useMutation: {
async onSuccess(opts) {
await opts.originalFn();
// This forces mutations to wait for all the queries on the page to reload, and in
// this case one of the queries is `searchDocument` for the command overlay, which
// on average takes ~500ms. This means that every single mutation must wait for this.
await opts.queryClient.invalidateQueries(); 
},
},
},
});
``` …
=> fix: update document flow fetch logic

packages/lib/server-only/document/seal-document.ts, packages/lib/server-only/pdf/flatten-annotations.ts, packages/lib/server-only/pdf/normalize-signature-appearances.ts, packages/signing/helpers/add-signing-placeholder.ts
This change flattens and normalizes annotation and widget layers within the PDF document removing items that can be accidentally modified after signing which would void the signature attached to the document.
Initially this change was just to assign to an ArcoForm object in the document catalog if it existed but quickly turned into the above. 
When annotations aren't flattened Adobe PDF will say that the signature needs to be validated and upon doing so will become invalid due to the annotation layers being touched.
To resolve this I set out to flatten and remove the annotations by pulling out their normal appearances if they are present, converting them into xobjects and then drawing those using the drawObject operator.
This resolves a critical issue the users experienced during the …
=> fix: normalize and flatten annotations

packages/ui/styles/theme.css
Currently opening modals, clicking select boxes or using anything from radix that overlays the screen in some way will shift the screen.
This can be easily noticeable when changing the document "Period" selector on the /documents page.
Undo the gutter change for now. Can find a proper solution another time.
https://github.com/documenso/documenso/assets/20962767/5bcae576-2944-4ae5-a2c3-0589e7f61bdb
=> fix: remove scrollbar gutter

packages/app-tests/e2e/pr-718-add-stepper-component.spec.ts, packages/app-tests/e2e/test-auth-flow.spec.ts, packages/lib/server-only/2fa/is-2fa-availble.ts
Fixed issue where accounts that were initially created via email/password, then linked to an SSO account, can bypass the 2FA during login if they use their email password.
Tested locally, and 2FA is now required for linked SSO accounts
=> fix: enforce 2FA for email password SSO linked accounts

.env.example
The `.env.example` had duplicate keys so removed them in this PR
=> chore: remove duplicate env vars

packages/lib/server-only/document/seal-document.ts
Fetch the updated version of the document after sealing it and return it. Previously, the `document.documentData.data` wasn't up to date. Now it is.
Fixes #1088.
* Added console.logs in the code to make sure it returns the proper data
* Set up a webhook and tested that the webhook receives the updated data
=> fix: return updated doc

packages/api/v1/implementation.ts, packages/api/v1/schema.ts, packages/lib/server-only/document/create-document.ts, packages/lib/server-only/document/send-document.tsx, packages/lib/server-only/pdf/insert-form-values-in-pdf.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/prisma/migrations/20240408083413_add_form_values_column/migration.sql, packages/prisma/schema.prisma
Adds the ability to prefill native PDF form fields via the API using either normal documents or templates.
Since we won't always know when a document is uploaded and has forms we opt to do this on creation for templates and on sending the document to recipients in all cases. This means that for a created document it can look a little funky since the form fields are missing the data until the document is sent.
This should be improved in a later change but since we've scoped this to an API only workflow for now we are less concerned with the visual issues.
N/A
- Added the `formValues` field the document model
- Added a new method for finding and filling form fields based on a `key | value` pair
- Updated the API input shapes to take the new field.
- Have created and tested a document using …
=> feat: add prefilling pdf form fields via api

apps/web/src/app/(dashboard)/documents/[id]/edit/document-edit-page-view.tsx, apps/web/src/app/(dashboard)/documents/[id]/loading.tsx, apps/web/src/app/(dashboard)/documents/[id]/logs/document-logs-page-view.tsx
General UI updates
- Add consistent spacing between document edit/view/log pages
- Add document status to document audit log page
- Update document loading page to reserve space for the document status below the title
- Update the document audit log page to show full dates in the correct locale
=> fix: improve document loading ui consistency

packages/lib/types/document-audit-logs.ts
When document audit logs were first introduced, we by default set the `fieldSecurity` to `NONE`
Now that document auth has been added, this is causing issues since we do not use `NONE` to define field that has no migrations required, but rather have the `fieldSecurity` field itself be undefined.
To keeps things consistent, this migration replaces `NONE` with undefined. 
There are a few ways to approach this:
- Run a prisma migration on the JSON
- Modify the data before we pass the data to the schema in `parseDocumentAuditLogData`
- Use `NONE` instead of undefined
If anyone thinks there's a better way to do this, please drop a comment 🙇
=> fix: document audit log field security migration

apps/marketing/src/components/(marketing)/footer.tsx
- removing widget since stability fix seems somehow worse in prod
=> fix: remove status widget for now

apps/web/src/app/(dashboard)/documents/[id]/document-page-view-dropdown.tsx
Adds a link from the document page view to the document page log view
=> feat: add document log page link

apps/web/src/app/(dashboard)/documents/[id]/logs/document-logs-page-view.tsx, apps/web/src/app/(dashboard)/documents/[id]/logs/download-certificate-button.tsx, packages/trpc/server/document-router/router.ts
Disable the document certificate download button when the document is not complete
- Disable UI button
- Disable TRPC API endpoint
Tested locally for pending, draft and completed documents
=> fix: disable cert download

packages/lib/server-only/webhooks/get-webhooks-by-user-id.ts
Currently if you create a team webhook, you can see it in your personal webhooks.
However, interacting with them will throw errors because there is server side logic preventing any interaction with them since they are outside of the correct context.
So the solution is to either:
- Allow the user to edit the team webhooks that they created on their personal webhooks page
- Hide team webhooks for personal webhooks pages
This PR goes with the second option, but is open to suggestions.
=> fix: hide team webhooks from users

package-lock.json, package.json, packages/lib/package.json, packages/lib/server-only/htmltopdf/get-certificate-pdf.ts
Upgrade playwright once again and use CDP for remote connections to avoid version lock-in with `playwright.connect`
Resolves the issue where all CI is failing currently due to downgrading playwright.
=> fix: use cdp and upgrade playwright again

packages/lib/universal/get-feature-flag.ts
Feature flags are broken on SSR due to this error
```
TypeError: fetch failed
at Object.fetch (node:internal/deps/undici/undici:11731:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
cause: RequestContentLengthMismatchError: Request body length does not match content-length header
at write (node:internal/deps/undici/undici:8590:41)
at _resume (node:internal/deps/undici/undici:8563:33)
at resume (node:internal/deps/undici/undici:8459:7)
at [dispatch] (node:internal/deps/undici/undici:7704:11)
at Client.Intercept (node:internal/deps/undici/undici:7377:20)
at Client.dispatch (node:internal/deps/undici/undici:6023:44)
at [dispatch] (node:internal/deps/undici/undici:6254:32)
at Pool.dispatch (node:internal/deps/undici/undici:6023:44)
at [dispatch] …
```
=> fix: ssr feature flags

apps/web/src/pages/api/trpc/[trpc].ts
Increase the max duration of the TRPC API endpoint to 120 seconds.
=> fix: increase trpc max duration

packages/lib/server-only/document/delete-document.ts
Currently deleting a pending document where you are a recipient off will delete the document, but will also throw an error.
This is due to the recipient being updated after the document deleted, which is only supposed to happen for completed documents.
_Preference is to not merge until playwright is resolved since there's a lot of document deleting E2E tests._
=> fix: delete pending documents

packages/lib/server-only/document/complete-document-with-token.ts, packages/lib/server-only/document/seal-document.ts, packages/lib/server-only/htmltopdf/get-certificate-pdf.ts
Improves the sealing process by being strict on how long certificate generation can take, opting to fail generation and continue sealing.
Also changes the ordering of sealing so an error in the process won't also cause a document to be "COMPLETED" since it hasn't been cryptographically sealed yet.
The downside to this change is that documents that fail during sealing will require manual intervention as a signer or owner won't be able to *complete* the document.
- Modified code to force specific failure modes to occur and verified that documents were either gracefully sealed without a certificate or not sealed and not completed.
=> fix: improve sealing process

apps/web/src/pages/api/auth/[...nextauth].ts
Currently users who sign in via Google SSO do not get assigned a Stripe customer account.
This enforces the Stripe customer requirement on sign in.
There might be a better place to put this so it's open to any suggestions.
=> fix: enforce users to have stripe account

apps/marketing/src/app/(marketing)/singleplayer/client.tsx, apps/web/src/app/(dashboard)/documents/upload-document.tsx, apps/web/src/app/(dashboard)/templates/new-template-dialog.tsx, packages/api/v1/implementation.ts, packages/ee/server-only/stripe/webhook/on-early-adopters-checkout.ts, packages/lib/constants/feature-flags.ts, packages/lib/server-only/document/seal-document.ts, packages/lib/server-only/document/send-document.tsx, packages/lib/universal/upload/put-file.ts, packages/trpc/server/singleplayer-router/router.ts
Currently if you complete a pending encrypted document, it will prevent the document from being sealed due to the systems inability to decrypt it.
This PR disables uploading any documents that cannot be loaded as a temporary measure.
**Note**
This is a client side only check
- Disable uploading documents that cannot be parsed
- Refactor putFile to putDocumentFile
- Add a flag as a backup incase something goes wrong
=> fix: disable encrypted pdfs

apps/web/src/app/(dashboard)/templates/[id]/template-page-view.tsx, apps/web/src/app/(dashboard)/templates/use-template-dialog.tsx, packages/api/v1/implementation.ts, packages/app-tests/e2e/templates/manage-templates.spec.ts, packages/lib/constants/template.ts, packages/lib/errors/app-error.ts, packages/lib/server-only/template/create-document-from-template-legacy.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/trpc/server/template-router/router.ts, packages/trpc/server/template-router/schema.ts, packages/ui/primitives/template-flow/add-template-placeholder-recipients.tsx
Refactor the "use template" flow
- Add placeholders for recipients
- Add audit log when document is created
- Trigger DOCUMENT_CREATED webhook when document is created
- Remove role field when using template
- Remove flaky logic when associating template recipients with form recipients
- Refactor to use `Form`
=> feat: add general template enhancements

packages/lib/client-only/download-pdf.ts
Modifies the generated filename for the downloaded PDF by appending "_signed" to the base title.
N/A
- Update the filename in the downloadFile function call to append "_signed" to the baseTitle variable.
Tested the `downloadPDF` function locally to ensure that the downloaded PDF file has the correct filename with "_signed" appended.
=> fix: downloaded files should have _signed

packages/api/v1/contract.ts, packages/api/v1/implementation.ts, packages/api/v1/schema.ts, packages/app-tests/e2e/api/v1/team-user-management.spec.ts, packages/app-tests/package.json, packages/lib/server-only/public-api/create-api-token.ts, packages/lib/server-only/public-api/delete-api-token-by-id.ts, packages/lib/server-only/public-api/get-all-user-tokens.ts, packages/lib/server-only/public-api/get-api-token-by-token.ts, packages/prisma/seed/teams.ts
Adds user management capabilities to our current API. Allows for adding, removing, listing and updating members of a given team using a valid API token.
N/A
- Added an endpoint for inviting a team member
- Added an endpoint for removing a team member
- Added an endpoint for updating a team member
- Added an endpoint for listing team members
Tests were written for this feature request
=> feat: add team user management endpoints to api

apps/web/src/app/(signing)/sign/[token]/signing-page-view.tsx, packages/email/template-components/template-document-invite.tsx, packages/email/templates/document-invite.tsx, packages/lib/jobs/definitions/emails/send-signing-email.ts, packages/lib/server-only/document/get-document-by-token.ts, packages/lib/server-only/document/resend-document.tsx
Fix the wrong message on the signing pages and emails.
=> fix: wrong signing invitation message

package.json
Clean redundant translations by default.
This should stop the AI from doing strange things to commented out translations.
=> chore: remove redundant translations on upload

packages/lib/constants/auth.ts, packages/lib/next-auth/auth-options.ts, packages/trpc/server/auth-router/router.ts
Currently passkeys are failing due to missing secure cookies prefix.
- Extract and reuse secure cookies logic
=> fix: secure passkey cookies

packages/api/v1/implementation.ts, packages/api/v1/schema.ts, packages/app-tests/e2e/api/v1/document-sending.spec.ts, packages/lib/server-only/document/send-completed-email.ts, packages/lib/types/document-email.ts, packages/ui/components/document/document-email-checkboxes.tsx
Adds a new `ownerDocumentCompleted` to the email settings that controls whether a document will be sent to the owner upon completion.
This was previously the only email you couldn't disable and didn't account for users integrating with just the API and Webhooks.
Also adds a flag to the public `sendDocument` endpoint which will adjust this setting while sendint the document for users who aren't using `emailSettings` on the `createDocument` endpoint.
Customer reported
- Added `ownerDocumentCompleted` to emailSettings meta
- Updated the UI to include a new checkbox that corresponds to `ownerDocumentCompleted`
- Added support in the API for setting `ownerDocumentCompleted` within the `sendDocument` endpoint
- E2E tests were written for the `sendDocument` endpoint
- Other manually ran tests …
=> feat: add controls for sending completion emails to document owners

packages/tailwind-config/index.cjs, packages/ui/primitives/document-flow/advanced-fields/checkbox.tsx, packages/ui/primitives/document-flow/advanced-fields/radio.tsx, packages/ui/styles/theme.css
Fixed Radio Button and Checkbox Appearance in Dark Mode 
Fixes #1513 
- `document-flow/advanced-fields/radio.tsx` - Added Tailwind CSS class to disable switch on dark mode.
- `document-flow/advanced-fields/checkbox.tsx` - Added Tailwind CSS class to disable switch on dark mode.
- `theme.css` - added `field-border` var
- Tailwind `baseConfig` - added `field-border` var
https://www.loom.com/share/efe8a33097a740f2874ca19e3db0602b?sid=4611d0a9-e019-440d-853b-c2d6ecac25f2
=> fix: darkmode on radio button and checkbox labels 

packages/ui/primitives/signature-pad/signature-pad.tsx
---
---
This PR adds a `select-none` class to the signature pad in order to prevent iPadOS from becoming too trigger happy with the context menu and auto corrects. Please ensure this doesn't break anything by accident.
I know this could present an issue with typed signatures, but those should be workable without select/paste.
- add a `select-none` to the signature pad container div
I didn't have the time yet to get a local setup to work, so please run a manual test before accepting. Sorry for the inconvenience.
=> chore: prevent user selection within signature pad

.github/workflows/e2e-tests.yml
Tests have begun to fail randomly due to upstream issues.
Pin E2E tests action to run on ubuntu-22.04
Notes:
- Updating playwright to ~1.49.1 did not resolve the issue
=> fix: tests

packages/lib/utils/advanced-fields-helpers.ts, packages/ui/primitives/document-flow/add-fields.tsx
fixes https://github.com/documenso/backlog-internal/issues/230
Open the advanced settings tab when the field gets placed on the document in the document editor.
https://github.com/user-attachments/assets/a7565f77-22c5-4a33-8c99-69b37fb61016
=> feat: open the advanced settings automatically

apps/web/src/app/(dashboard)/documents/upload-document.tsx, packages/lib/server-only/document/create-document.ts, packages/trpc/server/document-router/router.ts, packages/trpc/server/document-router/schema.ts
Passes the timezone of the user uploading the document/template via the UI to the server.
If the user uploads a document/template via the API and doesn't set a timezone, it defaults to `Etc/UTC`. 
- Changed my machine's timezone and uploaded a document via the UI.
✅ The correct timezone was set.
- I created a template via the UI.
✅ The correct timezone was set.
- I generated a document from the template.
✅ The correct timezone was set.
- I created a document via the API without setting a timezone.
✅ The default `UTC` timezone was set.
- I created a document via the API and specified a timezone.
✅ The correct timezone was set.
- I changed my machine's timezone again and repeated the whole process.
✅ The correct timezones were set.
=> fix: default to user timezone

apps/web/src/app/(dashboard)/templates/use-template-dialog.tsx, packages/app-tests/e2e/templates/create-document-from-template.spec.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/trpc/server/template-router/router.ts, packages/trpc/server/template-router/schema.ts
Adds the ability to upload a custom document when using a template.
This is useful when you have a given fixed template with placeholder values that you want to decorate with Documenso fields but will then create a final specialised document when sending it out to a given recipient.
Raised via user interviews.
- Added the ability to upload a custom document when using a template
- Updated the createDocumentFromTemplate endpoint to accept an optional custom documentDataId argument
- Created a document from a template the same way as usual
- Created a document while providing a custom document
- Verified behaviour is as expected
=> feat: allow switching document when using templates

apps/web/src/app/(signing)/sign/[token]/date-field.tsx, apps/web/src/app/(signing)/sign/[token]/email-field.tsx, apps/web/src/app/(signing)/sign/[token]/name-field.tsx, apps/web/src/app/(signing)/sign/[token]/number-field.tsx, apps/web/src/app/(signing)/sign/[token]/text-field.tsx, packages/lib/server-only/pdf/insert-field-in-pdf.ts, packages/lib/types/field-meta.ts, packages/ui/primitives/document-flow/field-item-advanced-settings.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/date-field.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/email-field.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/initials-field.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/name-field.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/number-field.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/text-field.tsx
Adds the ability to align text to the left, center or right for relevant fields.
Previously text was always centered which can be less desirable.
See attached debug document which has left, center and right text alignments set for fields.
N/A
- Added text align option
- Update the insert in pdf method to support different alignments
- Added a debug mode to field insertion
- Ran manual tests using the debug mode
=> feat: add text align option to fields

packages/email/template-components/template-document-invite.tsx
Updates one of our confusing ternaries to use `ts-pattern` for rendering the conditional blocks making it easy to follow the logic occurring.
N/A
- Swapped ternary for `ts-pattern`
- Manually created a bunch of documents in configurations matching those required to exhaust the `match` conditions.
=> fix: tidy document invite email render logic

packages/lib/server-only/team/create-team.ts
The global team settings weren't created when creating a new team.
The global team settings are now created when a new team is created.
=> fix: create global settings on team creation

apps/web/src/app/(signing)/sign/[token]/checkbox-field.tsx
https://github.com/user-attachments/assets/de18a53d-1065-4647-b612-6eba109a9bfb
https://github.com/user-attachments/assets/a486e280-ebd8-4abe-b9a4-465762e350bf
This change prevents race conditions between state updates and API operations by updating local state immediately before making async calls.
- Refactored the `handleCheckboxOptionClick` function to consolidate API calls:
- Fixed a bug where `checkedValues` was being used in `toCheckboxValue` before being updated
=> fix: unable to check on the checkbox field

apps/web/src/app/(recipient)/d/[token]/sign-direct-template.tsx, apps/web/src/app/(signing)/sign/[token]/signing-page-view.tsx
The `typedSignatureEnabled` prop was removed from the `SignatureField` component, which broke the typed signature meaning that nobody could sign documents by typing their signature.
=> fix: typed signature not working

packages/ee/server-only/stripe/get-prices-by-plan.ts
Currently Stripe prices search is omitting a price for an unknown reason.
Changed our fetch logic to use `list` instead of `search` allows us to work around the issue.
It's unknown on the performance impact of using `list` vs `search`
1. Ran old and new fetches
2. Diffed results
3. New result showed the missing price
Simplified testing:
```typescript
const oldResult = await oldGetPricesByPlan(['regular', 'community', 'platform', 'enterprise']);
const newResult = await newGetPricesByPlan(['regular', 'community', 'platform', 'enterprise']);
console.log({
oldResultPriceLength: oldResult.length, // 13
newResultPriceLength: newResult.length, // 14
});
```
=> fix: stripe price fetch

packages/ui/primitives/document-flow/add-signers.tsx
https://github.com/user-attachments/assets/25e20a7f-d00a-48af-9e7c-392700bba9b1
https://github.com/user-attachments/assets/37b8e866-344b-455a-b919-58f44f93b3d9
This PR fixes a bug in the signer removal functionality in the document flow. Previously, signers were being removed based on array index which could lead to incorrect removals if the form state and visual state were out of sync. The fix ensures signers are removed based on their unique `formId` instead.
- Modified signer removal logic in `AddSignersFormPartial` component to use `formId` for identifying signers
- Updated form state management to properly filter signers based on `formId` instead of array index
- Ensured signing order normalization is maintained after signer removal
=> fix: correct signer deletion

apps/web/src/app/(dashboard)/documents/[id]/logs/document-logs-page-view.tsx
This PR fixes a UI issue on the document logs page where the download button gets cut off on small screens. The fix ensures the button remains fully visible by adjusting the layout and spacing for better responsiveness.
Fixes #1627 
- Removing `justify-between` from the outer div – ensuring that elements are no longer forcefully spaced apart.
- Separating `title` into its own div – preventing layout shifts.
- Wrapping the status and buttons in a flex container – ensuring they align properly in a row for larger screens and stack on smaller ones.
- Adding `truncate` to document information values – ensuring long values don’t overflow.
[documenso-1627-before.webm](https://github.com/user-attachments/assets/f161fa1b-3d88-4011-b171-b25c66baa06f) …
=> fix: improve layout and truncate document information in logs page

apps/web/src/components/(dashboard)/layout/desktop-nav.tsx
This PR fixes a UI issue on the `https://app.documenso.com/documents` page where the Header gets cut off on small screens. The fix ensures the Header/Navbar remains fully visible by adjusting the layout and spacing for better responsiveness.
Fixes: #1698 
The width has been changed from 'w-96' to 'w-full.'
[documenso-1698.webm](https://github.com/user-attachments/assets/dcddc50c-27db-41d1-badf-59f83481785e)
=> fix: adjust desktop nav search button width and spacing

apps/remix/app/components/general/direct-template/direct-template-signing-form.tsx, apps/remix/app/components/general/document-signing/document-signing-checkbox-field.tsx
The changes in `sign-direct-template.tsx` automatically fill in field values for text, number, and dropdown fields when default values are present or if the fields are read-only. In `checkbox-field.tsx`, the changes fix the checkbox signing by checking if the validation is met and improving how it saves or removes checkbox choices.
I tested the code locally with a variety of documents/fields.
=> fix: autosigning fields with direct links

apps/remix/app/components/dialogs/assistant-confirmation-dialog.tsx, apps/remix/app/components/general/document-signing/document-signing-form.tsx, packages/app-tests/e2e/document-auth/next-recipient-dictation.spec.ts, packages/app-tests/e2e/teams/team-signature-settings.spec.ts, packages/lib/translations/de/web.po, packages/lib/translations/en/web.po, packages/lib/translations/es/web.po, packages/lib/translations/fr/web.po, packages/lib/translations/it/web.po, packages/lib/translations/pl/web.po, packages/trpc/server/document-router/update-document.ts, packages/ui/primitives/toast.tsx
Fix webhooks being sent twice due to duplicate frontend calls
Updated the assistant confirmation dialog so the next signer is always visible (if dictate is enabled). Because if the form is invalid (due to no name) there is no visual queue that the form is invalid (since it's hidden)
Didn't bother to remove the weird assistants form since it currently works for now
- Currently running locally
- Tested webhooks via network tab and via webhook.site
=> fix: duplicate webhook calls on document complete

apps/remix/app/components/general/direct-template/direct-template-page.tsx
Currently direct template redirects are broken because we are incorrectly using `navigate` to redirect to an external website.
Tested both redirects and no redirects for direct templates, both work as intended.
=> fix: direct template redirects

apps/remix/app/components/embed/embed-document-signing-page.tsx, apps/remix/app/components/general/document-signing/document-signing-page-view.tsx, apps/remix/app/components/general/document/document-read-only-fields.tsx, apps/remix/app/routes/embed+/sign.$url.tsx, apps/remix/app/types/embed-document-sign-schema.ts
Previously we weren't passing the DocumentMeta to our readonly field component which is used for displaying completed fields by other recipients.
Due to this dates that were not using the default format were displaying as invalid date adding confusion to the signing process.
Reported via support email.
- Pass the document meta to the readonly field component.
- Support showing completed fields within the embedding UI.
- Manual testing
=> fix: pass document meta to readonly field component

apps/remix/app/components/tables/admin-leaderboard-table.tsx, apps/remix/app/routes/_authenticated+/admin+/leaderboard.tsx, packages/lib/server-only/admin/get-signing-volume.ts
This pull request updates the implementation of the admin leaderboard, enhancing data handling and improving type safety. It introduces clearer differentiation between users and teams, adds additional fields to track more relevant information, and refactors the querying logic to optimize performance and maintainability.
- Refactored `getSigningVolume` from a Kysely query to Prisma ORM for improved readability and consistency.
- Implemented logic to distinguish between team and user subscriptions, aggregating their respective document counts accurately.
- Added sorting and pagination logic with clearer variable naming and improved data validation.
=> fix: signing volume query

packages/lib/server-only/template/create-document-from-template.ts, packages/lib/types/field-meta.ts
Allows the prefilling of date fields when creating a document from a template.
Current implementation is super dirty and should be replaced asap.
=> fix: allow prefilling date field

apps/remix/app/components/general/document-signing/document-signing-field-container.tsx, packages/ui/components/field/field-tooltip.tsx
Makes it so clicking on the pending field tooltip will trigger the underlying field it refers to on click if the field can be found within the DOM.
=> fix: pending tooltip click triggers field

apps/remix/app/routes/_authenticated+/admin+/stats.tsx, packages/lib/server-only/admin/get-users-stats.ts
Fixes MAU (Monthly Active Users) metrics that were broken. The admin dashboard was showing empty charts because the underlying SQL queries were still using the old database schema structure. After the organization migration, documents now belong to teams, and teams belong to organizations, but the MAU queries were still trying to access documents directly from users.
- Fixed SQL queries in to work with new organization structure
- Tested that MAU charts now display actual data instead of empty charts
=> fix: admin metrics broken

apps/remix/app/components/general/document/document-edit-form.tsx, apps/remix/app/components/general/template/template-edit-form.tsx, packages/ui/primitives/document-flow/add-settings.types.ts, packages/ui/primitives/template-flow/add-template-settings.types.tsx
Users can't proceed further if they select the `No restrictions` option for the `Document Access` field in the document/template editor.
Updated the `globalAccessAuth` field in the Zod schemas from `add-template-settings.types.tsx` and `add-settings.types.ts`:
```tsx
globalAccessAuth: z
.array(z.union([ZDocumentAccessAuthTypesSchema, z.literal('-1')]))
.transform((val) => (val.length === 1 && val[0] === '-1' ? [] : val))
.optional()
.default([]),
```
It converts the `-1` value, which represents the `No restrictions` option , into an empty array, which also serves as the default value.
Uploaded various documents and templates with various options for the `Document Access` field. Then, I checked the database to make sure it reflects the correct values.
=> fix: globalAccessAuth error

packages/lib/server-only/document/duplicate-document-by-id.ts, packages/lib/server-only/template/duplicate-template.ts
Previously, duplicating documents created empty shells without fields or recipients, and template duplication lost all advanced field configurations. These changes implement proper deep cloning to create true functional copies.
- Create new recipients and fields for the new duplicated document
- Added `fieldMeta` property to field creation in template duplication to preserve advanced settings
=> fix: duplicate fields and recipients when you duplicate a document

apps/remix/app/components/dialogs/organisation-member-invite-dialog.tsx, apps/remix/app/components/dialogs/team-create-dialog.tsx, apps/remix/app/components/general/organisations/organisation-billing-banner.tsx, apps/remix/app/routes/_authenticated+/o.$orgUrl.settings.billing.tsx, apps/remix/app/routes/_unauthenticated+/articles.signature-disclosure.tsx, packages/lib/constants/app.ts
Currently users who cancel their plan are stuck without the ability to resubscribe. This allows them to choose a plan to subscribe 
This assumes that a Subscription in the "INACTIVE" state means that the plan has been paid but canceled.
No tests have been done to determine the relation between "PAST_DUE" and "INACTIVE" states within our context.
=> fix: allow resubscribing

apps/remix/app/components/dialogs/organisation-create-dialog.tsx, apps/remix/app/components/general/billing-plans.tsx, packages/ee/server-only/stripe/webhook/on-subscription-updated.ts, packages/trpc/server/billing/create-subscription.ts, packages/trpc/server/billing/create-subscription.types.ts
Prevent users from creating a separate organisation for individual plans. Only appllies to users who have 1 personal organisation and are subscribing to the "Individual" plan.
The reason for this change is to keep the layout in the "Personal" mode which means it doesn't show a bunch of unusable "organisation" related UI.
=> fix: restrict individual plans to upgrade only

apps/remix/app/components/dialogs/document-move-to-folder-dialog.tsx, apps/remix/app/components/tables/documents-table-action-dropdown.tsx, packages/lib/server-only/folder/move-document-to-folder.ts
- Adds error handling for unauthorized document moving in the `DocumentMoveToFolderDialog` component.
- Displays a toast notification when the recipient tries to move a document. 
- Updates the `DocumentsTableActionDropdown` to disable the move option if the user is not the owner of the document.
- Ensures server-side validation checks for user permissions before moving documents.
=> fix: handle unauthorized document move error

packages/ui/components/document/document-signature-settings-tooltip.tsx
In "Organization Settings" and "Team Settings" preferences pages, a click on the tooltip information icon submit the page form, which is unexpected.
To reproduce this issue:
- navigate to organization settings preferences page
- next to the form input label "Default Signature Settings", click on the information icon (circled "i")
- the page form is submitted (you get the popup "Document preferences updated")
Changed the tooltip icon button type to "button", as it is done in some other places in the project.
Tested on Safari and Firefox (macOS).
=> fix: clicking on tooltip icon submit parent form

apps/remix/app/components/general/document-signing/document-signing-fields.tsx
Currently new lines are not rendered in text fields correctly on the `/sign` page. This is an issue because when the field is inserted and sealed we respect new lines.
**Previous**
**New**
=> fix: correctly render new lines in text fields

packages/lib/server-only/htmltopdf/get-certificate-pdf.ts
Certificates have suddenly become blank when using browserless and Chrome CDP.
This change introduces a workaround that involves reloading the certificate pdf. Which is hacky but seems to work for now, a better solution should be found in the future.
=> fix: certificate pdfs are blank when using browserless

apps/remix/app/components/general/document/document-edit-form.tsx, apps/remix/app/components/general/template/template-edit-form.tsx, apps/remix/app/routes/_authenticated+/o.$orgUrl.settings.email-domains.$id.tsx, packages/lib/jobs/definitions/emails/send-document-cancelled-emails.handler.ts, packages/lib/jobs/definitions/emails/send-recipient-signed-email.handler.ts, packages/lib/jobs/definitions/emails/send-rejection-emails.handler.ts, packages/lib/jobs/definitions/emails/send-signing-email.handler.ts, packages/lib/server-only/document/delete-document.ts, packages/lib/server-only/document/resend-document.ts, packages/lib/server-only/document/send-completed-email.ts, packages/lib/server-only/document/send-delete-email.ts, packages/lib/server-only/document/send-pending-email.ts, packages/lib/server-only/document/super-delete-document.ts, packages/lib/server-only/email/get-email-context.ts, packages/lib/server-only/recipient/delete-document-recipient.ts, packages/lib/server-only/recipient/set-document-recipients.ts, packages/trpc/server/document-router/schema.ts, packages/trpc/server/document-router/update-document.types.ts, packages/trpc/server/template-router/schema.ts, packages/ui/primitives/document-flow/add-subject.types.ts, packages/ui/primitives/template-flow/add-template-settings.types.tsx
General fixes to the email domain features
Changes made:
- Add "email" validation for "Reply-To email" fields
- Fix issue where you can't remove the "Reply-To" email after it's set
- Fix issue where setting the "Sender email" back to Documenso would still send using the org/team pref
=> fix: add missing email reply validation

apps/remix/app/components/dialogs/team-member-create-dialog.tsx
Adding team members can create confusion because you first need to add the member to the organization. We received support queries about this and I also got confused.
If not needed, feel free to close it.
=> feat: add tooltip to team member creation dialog for guidance

apps/remix/app/routes/_authenticated+/t.$teamUrl+/documents.$id._index.tsx, apps/remix/app/routes/_authenticated+/t.$teamUrl+/documents.$id.edit.tsx, apps/remix/app/routes/_authenticated+/t.$teamUrl+/documents.$id.logs.tsx, packages/lib/utils/logger.ts
Add logging when someone accesses a document page:
- /documents/id
- /documents/id/edit
- /documents/id/logs
=> fix: add document page access logging

packages/lib/server-only/document/get-document-by-id.ts, packages/trpc/server/trpc.ts
Update the TRPC procedure to correctly output the intended context type for "teamId".
For some reason it currently assumes there is a `teamId` due to returning two different types of data, one for API and one for session
=> fix: add dummy teamid

apps/remix/app/routes/_authenticated+/t.$teamUrl+/documents.$id.logs.tsx
For Documents stored in team subfolders, clicking "Audit Log" would redirect users back to the team's root documents folder instead.
=> fix: access audit logs for documents in folder

apps/remix/app/components/dialogs/document-resend-dialog.tsx, packages/ui/primitives/document-flow/add-signers.tsx
The checkboxes were difficult to see and the "Send reminder" button wasn't disabled when no recipients were selected. This PR disables the sending button when there's no selected recipient and improves the checkboxes visibility.
=> feat: resend dialog improvements

apps/remix/app/components/general/document-signing/document-signing-page-view.tsx, packages/lib/server-only/document/get-document-by-token.ts
If the team has the branding enabled & a logo uploaded, it'll show on the document signing page view.
Tested that the branding logo is displayed on both the logged-in & non-logged-in document signing pages.
=> feat: show branding logo on signing page

packages/auth/server/lib/utils/handle-oauth-authorize-url.ts, packages/auth/server/routes/oauth.ts
Use the `select_account` prompt for SSO OIDC to avoid constantly asking for credentials to be entered with a client has an existing session with the SSO provider.
=> fix: use select account prompt for sso oidc
