apps/web/components/navigation.tsx
=> Route to Profile on Settings

packages/lib/mail/sendSigningRequest.ts
=> Custom message if name is defined or null in email template

apps/web/components/navigation.tsx
=> Close panel on when user clicks on a nav link

apps/web/pages/documents/[id]/recipients.tsx
fixes #23 
waiting for reviews
=> Added margins and borders

apps/web/pages/documents/[id]/recipients.tsx, packages/ui/components/dialog/Dialog.tsx, packages/ui/components/dialog/index.ts, packages/ui/index.ts
=> Make dialog into a component

packages/pdf/insertTextInPDF.ts
Previously, inserted text would appear a little off center from where the user had selected which could cause some frustration.
We improve upon this by updating the code responsible for centering the text to behave in a more accurate manner. From what I can tell it looks to be quite solid but could do with more rigorous testing with shorter and longer inputs.
You can see the improved accuracy in action here:
https://www.loom.com/share/1095fee7605c4790b8b30f573a04f0f0
=> fix: improve text insertion accuracy

apps/web/components/editor/recipient-selector.tsx
ListBox options must be unique
|  |  preview |
| ------- | --- | 
| Before | ![086b7e6baaea9f3e92ac67ed36f0af53](https://user-images.githubusercontent.com/65268462/230461128-7cc47724-4cc0-445c-b87a-30ef328a0cb4.png)|
| After | ![0df1e45febd95bc11dbc704a1c20032e](https://user-images.githubusercontent.com/65268462/230461148-a8caccc5-c799-4933-87df-0750c5a32bdc.png)|
P.s this is my first commit to the repo, so just wanted to start with something small.
=> small fix for recipient-selector

apps/web/pages/api/documents/[id]/sign.ts, packages/lib/mail/sendSigningDoneMail.ts
=> Send email notification to signers on document signing completion

apps/web/pages/documents.tsx, apps/web/pages/documents/[id]/recipients.tsx, packages/prisma/seed.ts
=> Disable the edit and add signer button for completed documents

apps/web/pages/documents/[id]/recipients.tsx
=> Remove Input Placeholders

README.md
fixed typos on Readme.md file.
=> Fix: typos on Readme

apps/web/pages/documents.tsx
https://user-images.githubusercontent.com/66999381/234017573-4edf4206-cae6-4a51-a430-d02c37761fe2.mov
=> feat: Keep the URL query params and UI state in sync when status filter changes

apps/web/pages/documents.tsx, apps/web/pages/documents/[id]/recipients.tsx, packages/ui/components/tooltip/Tooltip.tsx, packages/ui/components/tooltip/index.ts, packages/ui/index.ts
=> Add tooltip to recipients action buttons

apps/web/pages/documents/[id]/sign.tsx
fixes https://github.com/documenso/documenso/issues/152
=> fix: pass recipient token to signed page

README.md
WE LAUNCH ON PRODUCT HUNT TOMORROW.
https://dub.sh/documenso-launch
=> PRODUCT HUNT LAUNCH TOMORROW

README.md
We are LIVE on Product Hunt 🚨 Come say hi :) 
https://www.producthunt.com/posts/documenso
=> We are LIVE on Product Hunt 🚨 Come say hi :)

apps/web/components/layout.tsx, apps/web/pages/_app.tsx, apps/web/styles/tailwind.css, apps/web/tailwind.config.js
Fixes #169 
Tested it locally and it builds without issues.
https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css
=> loading fonts with next/font for no layout shift

.gitignore, apps/web/next.config.js, package-lock.json, package.json, turbo.json
```bash
▲  documenso/ turbo run build            
• Packages in scope: @documenso/features, @documenso/lib, @documenso/pdf, @documenso/prisma, @documenso/signing, @documenso/ui, @documenso/web
• Running build in 7 packages
...
...
...
Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
Time:    156ms >>> FULL TURBO
```
=> Add turborepo to monorepo.

apps/web/components/navigation.tsx
=> fix: dashboard logo

package.json
Issue #175 
Package json script for docker updated, to work on various platforms
=> docker script updated 🐳

README.md
Product Hunt is over, its probably better to move it into its own section.
also added product of the day!
=> chore: fix readme Product Hunt Badges

apps/web/components/editor/pdf-editor.tsx
=> Fix typo in pdf-editor.tsx

packages/lib/stripe/handlers/webhook.ts
Improve the stripe webhook endpoint by checking for subscriptions prior to performing an update to handle cases where accounts have no created subscription.
This can happen in sitations such as when a checkout_session has been created but the payment fails.
=> fix: improve stripe webhook endpoint

README.md
link taken from https://documenso.com/pricing
=> added new cal.com badge for booking link

manifest.md
The Documenso Manifesto describe the cultures and future we are setting out to build. By placing it at the core of the project we want to anker this deeply in everythign we do.
=> feat: added manifest

README.md
=> chore: claim

CONTRIBUTING.md, README.md, apps/marketing/content/blog/switching-from-slack-to-discord
- this PR also updates the link to the Discord community in:
- README.md
- CONTRIBUTING.md
=> Add new blog post: Switching to Discord

CONTRIBUTING.md, apps/web/components/billing-plans.tsx, apps/web/components/editor/pdf-editor.tsx, apps/web/components/editor/signature-dialog.tsx, apps/web/pages/api/documents/[id]/send.ts, apps/web/pages/api/documents/[id]/sign.ts, packages/lib/server/getServerErrorFromUnknown.ts, packages/signing/addDigitalSignature.ts
Corrected some typos on ts and tsx files.
=> Fixed typos

apps/marketing/content/blog/pre-seed.mdx
=> Fix: typo in blog post `pre-seed`

.husky/commit-msg, commitlint.config.cjs, package-lock.json, package.json
Adds commit lint
Fixes #267
/claim #267
=> feat: add commitlint

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, README.md, package.json
- This PR adds dependabot and codeql workflows
- Also, updates the readme as well :)
- Enabled `engines` in `package.json` to enforce Node v18.0.0 and above
=> feat: added codeql and dependabot workflows

.env.gitpod, .gitpod.yml, README.md
You can test the `.gitpod.yml` config on the branch here:
https://gitpod.io/#https://github.com/documenso/documenso/tree/docs/add-gitpod-setup
=> docs: add gitpod setup

apps/marketing/src/components/(marketing)/claim-plan-dialog.tsx, apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx, apps/web/src/app/(dashboard)/documents/[id]/loading.tsx, apps/web/src/app/(signing)/sign/[token]/form.tsx, packages/lib/client-only/hooks/use-document-element.ts, packages/ui/primitives/button.tsx, packages/ui/primitives/document-flow/add-fields.tsx, packages/ui/primitives/document-flow/add-signers.tsx, packages/ui/primitives/document-flow/add-subject.tsx, packages/ui/primitives/document-flow/document-flow-root.tsx, packages/ui/primitives/document-flow/field-item.tsx, packages/ui/primitives/document-flow/types.ts, packages/ui/primitives/lazy-pdf-viewer.tsx, packages/ui/primitives/pdf-viewer.tsx, packages/ui/tailwind.config.cjs
Changes:
- Updated drag and drop fields
- Updated how height is calculated for PDFs and document flow
- Updated claim plan dialog
- Added button spinner
- Added animation for document flow slider
- Fixed z-index when dragging pre-existing fields
- Refactored document flow
Notes:
- Stacking issue still remains when dragging a new field
- Since the document flow now adjusts to the height of the PDF we may want to consider animating the height to reduce the jarring height change
=> feat: update document flow

packages/lib/next-auth/auth-options.ts, packages/lib/next-auth/error-codes.ts
currently the login process allows any random password as a legit password, this PR aims to fix that.
=> fix: authentication allowing any password

apps/marketing/package.json, apps/web/package.json, package-lock.json
While running `npm run build` I was seeing a warning to add `sharp` library. Please refer the SS below
More Info: https://nextjs.org/docs/messages/install-sharp
=> feat: added sharp package for NextJS13 image optimizations

apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/app/(signing)/sign/[token]/page.tsx
=> fix: make signing form card responsive

apps/web/src/app/(dashboard)/documents/page.tsx, apps/web/src/components/(dashboard)/period-selector/period-selector.tsx
=> fix: tab overflow on smaller viewport and tab scroll ux

.eslintrc.cjs, apps/web/src/components/(dashboard)/layout/desktop-nav.tsx, apps/web/src/pages/api/document/create.ts, package-lock.json, package.json, packages/eslint-config/index.cjs, packages/eslint-config/package.json, packages/prisma/tsconfig.json, packages/tailwind-config/package.json, packages/trpc/server/auth-router/schema.ts, packages/ui/primitives/card.tsx, packages/ui/primitives/navigation-menu.tsx
This PR removes unnecessary white space before or after the class names
Thought: How about we add an eslint rule, specifically this, https://eslint.org/docs/latest/rules/no-multi-spaces
=> fix: removed unnecessary whitespace before className

apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/app/(signing)/sign/[token]/signature-field.tsx
Removed two `console.logs` in components
=> chore: removed unnecessary `console.log`

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx, packages/trpc/server/document-router/router.ts
- Redirect to dashboard after document is sent
- Show a toast when document is sent
=> feat: redirect to dashboard when document is sent

apps/web/src/components/forms/profile.tsx
This PR basically adds an error message to the signature pad when empty .
=> feat: add error message to signature pad

packages/lib/server-only/document/complete-document-with-token.ts, packages/lib/server-only/document/seal-document.ts, packages/lib/server-only/pdf/insert-field-in-pdf.ts
Removed unneeded console.logs and warn.
=> chore: removed console logs and warn

apps/web/src/components/forms/signin.tsx, packages/lib/next-auth/auth-options.ts, packages/lib/next-auth/error-codes.ts, packages/ui/primitives/alert.tsx
[Screencast 2023-09-01 16:26:52.webm](https://github.com/documenso/documenso/assets/84864519/d05db848-e572-4dc9-b0f6-c83b0c5d6339)
=> feat: add alert banner for errors in sigin page

apps/marketing/src/components/(marketing)/mobile-navigation.tsx
Updated the mobile navigation for the marketing site with the following:
- Added the open page to the list of links
- Increased the speed of the animation and added an easing function
The animation changes are personal preference, let me know if the current animation is preferred and I will revert it.
=> feat: update marketing mobile nav

README.md
- This PR improves the instructions for running Documenso in docker
=> chore(docs): improve Docker instructions

apps/web/src/components/(dashboard)/layout/profile-dropdown.tsx
I noticed some anomaly in the theme section for user so added a dropdownmenusub for better user experience which will be more acceptable to user
example:-
=> feat: added a better theme change ability for user

apps/web/src/app/(dashboard)/documents/[id]/loading.tsx, apps/web/src/app/(dashboard)/documents/[id]/page.tsx, apps/web/src/app/(dashboard)/documents/[id]/sent/page.tsx
Removes max width on document titles
Resolves #447
=> fix: resolve document title inconsistency

apps/web/src/app/(dashboard)/admin/layout.tsx, apps/web/src/app/(dashboard)/documents/[id]/page.tsx, apps/web/src/app/(dashboard)/documents/page.tsx, apps/web/src/app/(dashboard)/layout.tsx, apps/web/src/app/(dashboard)/settings/billing/page.tsx, apps/web/src/app/(dashboard)/settings/password/page.tsx, apps/web/src/app/(dashboard)/settings/profile/page.tsx, apps/web/src/app/(signing)/sign/[token]/complete/page.tsx, apps/web/src/app/(signing)/sign/[token]/complete/share-button.tsx, apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/app/(signing)/sign/[token]/layout.tsx, apps/web/src/app/(signing)/sign/[token]/page.tsx, apps/web/src/app/not-found.tsx, apps/web/src/components/forms/edit-document/add-fields.action.ts, apps/web/src/components/forms/edit-document/add-signers.action.ts, apps/web/src/components/forms/edit-document/add-subject.action.ts, packages/lib/next-auth/get-server-session.ts, packages/lib/universal/upload/server-actions.ts, packages/trpc/server/context.ts, packages/ui/primitives/dialog.tsx
Removes an overflow which breaks element stickiness, also added enhancements to stickiness based on authentication state.
Resolves #432
=> fix: resolve issues with signing document stickiness

packages/ui/primitives/document-flow/add-fields.tsx
This PR adds an empty message to the recipient list.
Fixes #437
=> chore: add empty message

packages/ui/components/signing-card.tsx
=> fix: sharp corners of signing card

apps/web/src/components/forms/forgot-password.tsx, apps/web/src/components/forms/reset-password.tsx, apps/web/src/components/forms/signin.tsx, apps/web/src/components/forms/signup.tsx
Feature
When the `isSubmitting` prop is true the button text does not change:
https://github.com/documenso/documenso/assets/22655069/e0dd5cab-07c1-4797-90eb-dfceb9b969f4
Now the button text changes:
https://github.com/documenso/documenso/assets/22655069/6fb231ed-bdcb-4e9c-883f-0f2c4a73d4b8
=> feat: auth button loading texts

apps/marketing/src/components/(marketing)/claim-plan-dialog.tsx
=> fix: Error in Pricing Page Validation for Signup Now Modal

apps/web/src/components/forms/password.tsx, packages/lib/server-only/user/update-password.ts, packages/trpc/server/profile-router/router.ts, packages/trpc/server/profile-router/schema.ts
Fixes: https://github.com/documenso/documenso/issues/471
https://github.com/documenso/documenso/assets/53316345/22b92851-b819-420c-8d2b-1fee4c04f6cb
=> feat: require old password for password reset

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Changes:
- Add [code of conduct](https://www.contributor-covenant.org/)
- Update contributing guidelines
=> chore: add code of conduct

packages/trpc/server/auth-router/router.ts
=> fix: sign up with existing account email bug

apps/marketing/src/components/(marketing)/widget.tsx, packages/ui/primitives/dialog.tsx
Fixes #507 
Issue: 
Non Responsiveness of Add your signature modal 
After Fixes: Center aligned the modal content
Screenshot
=> fix: non responsiveness of Add your sign modal

.devcontainer/on-create.sh, README.md, package.json, packages/prisma/helper.ts, packages/ui/primitives/dialog.tsx
Fix #523 [DOC-36] Use dotenv for Prisma package scripts
=> fix(script): [fix : DOC-36] Use dotenv for Prisma package scripts #523

.gitpod.yml
Previously there was no gitpod.yml file to setup in gitpod. I've created the gitpod.yml and add required commands.
fixes #518 
result:-
=> fix: Add gitpod configuration

apps/web/src/app/(signing)/sign/[token]/signature-field.tsx
https://github.com/documenso/documenso/assets/145282438/ce002b13-300d-4ef5-841c-9d51280527b9
fixes #536
=> fix: bypass signature fix (#536)

apps/web/src/components/forms/profile.tsx, apps/web/src/components/forms/signup.tsx, packages/ui/primitives/signature-pad/signature-pad.tsx
Fixes: https://github.com/documenso/documenso/issues/483
=> fix: background color of signature page

packages/ui/primitives/document-flow/add-fields.tsx
Fixes: https://github.com/documenso/documenso/issues/564
With these changes now i can drag the field as well as click on the field and then click on the target
https://github.com/documenso/documenso/assets/53316345/919a2f6c-d1f1-47e6-8170-74e0b81b20ae
=> fix: enable dragging fields

apps/marketing/src/components/(marketing)/footer.tsx, apps/marketing/src/components/(marketing)/mobile-navigation.tsx
fixes #560 
I have added -- target: '_blank'  to support  link.
=> fix: support mailto link fix

apps/marketing/next.config.js, apps/web/next.config.js
This PR fixes #573 .
This PR solves error: invalid url on main page in self hosting.
=> fix: error invalid url on main page on self host #573

apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/app/(signing)/sign/[token]/name-field.tsx, packages/trpc/server/field-router/schema.ts
**fixes #555** 
**I have fixed in two places in singup form and profile update page form.
this fix improves UX as It disabled the update profile / singup button when ever the fullname was emtpy .
as shown in video below !**
**[updated video]**
https://www.loom.com/share/f0591258760349bc9871675a480972f4?sid=7617e340-a854-4f72-b70e-2756594686b4
If any changes required let me know !
Thank You :smile:
=> fix(bug): name field can be updated with spaces #555

apps/marketing/content/blog/building-documenso-pt1.mdx, apps/marketing/src/app/(marketing)/pricing/page.tsx, apps/marketing/src/components/(marketing)/pricing-table.tsx
This PR updated the slack link to the discord links 👀
=> chore: updated slack to discord links

README.md
Fixing https://github.com/documenso/documenso/issues/589
=> feat: update the README for the self-hosting users

package-lock.json, packages/ui/components/document/document-share-button.tsx
This PR fixes #605.
After Solution
[Screencast from 10-30-2023 11:05:38 AM.webm](https://github.com/documenso/documenso/assets/88766161/6eb4a309-38ad-4063-9ca3-db6d082dc34e)
=> fix: use web app url for share link copying

README.md
Add docker section to Deployment section
=> docs: Add docker compose instructions

apps/marketing/src/components/(marketing)/widget.tsx
=> fix: improve the early adopters plan input section

.github/ISSUE_TEMPLATE/bug-report.yml
Update the GitHub report template checklist to include whether the issue author wants to handle creating a PR for the issue if approved. 
Not actually sure if this is a good spot to put it
=> chore: update bug report template

apps/web/src/app/(dashboard)/documents/page.tsx, packages/lib/server-only/document/find-documents.ts
fixes #610 
https://www.loom.com/share/210110e20c3344d3b014f96d07932ae1
=> fix: days filter working

apps/marketing/src/components/(marketing)/single-player-mode/create-single-player-document.action.ts
Resolves issues surrounding signing/sealing/emailing SPM documents
Changes:
- Sign and email correct SPM document
- Optimize signing SPM documents
=> fix: correctly sign SPM documents

apps/web/src/app/(dashboard)/documents/page.tsx
https://github.com/documenso/documenso/assets/114291962/36e3b9b7-d9bd-473a-b2f4-cf2ea27cfa06
=> fix: hovering on tabslist items at dashboard

packages/ui/primitives/document-flow/add-signature.types.tsx
Issue fix #593 
Validation message fix the in Single Player Mode .
=> fix: added the zod validation msg in the single player mode

.github/workflows/ci.yml, apps/marketing/package.json, apps/web/package.json, apps/web/src/components/(dashboard)/layout/desktop-nav.tsx, package-lock.json, packages/email/mailer.ts
Set a default for smtp host and add an action for testing docker builds on each pull request
Closes #670
=> fix: docker build requires smtp host

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx, apps/web/src/components/forms/edit-document/add-title.action.ts, packages/lib/server-only/document/update-title.ts, packages/trpc/server/document-router/router.ts, packages/trpc/server/document-router/schema.ts, packages/ui/primitives/document-flow/add-signers.tsx, packages/ui/primitives/document-flow/add-title.tsx, packages/ui/primitives/document-flow/add-title.types.ts, packages/ui/primitives/document-flow/types.ts
Feature to add or update title to the documents. #660 
I've added the feature which provides the flexibility to users to have the custom title to their documents. 
These changes adds an input to the step form, which handles the title. See #660 for more information. 
**Added some action, types. 
Added some changes to the tRPC schema and tRPC document router.
Added some changes to the UI components.**
=> feat: add/update title of the Document

apps/marketing/next.config.js, apps/web/next.config.js
=> fix: body exeeded undefined limit

.eslintrc.cjs, .vscode/settings.json
=> fix: add workspace settings for eol and tabs

apps/web/src/app/(dashboard)/documents/data-table-action-dropdown.tsx, apps/web/src/app/(dashboard)/templates/[id]/edit-template.tsx, apps/web/src/components/forms/edit-template/add-template-placeholders.action.ts, packages/lib/server-only/admin/get-recipients-stats.ts, packages/lib/server-only/field/get-fields-for-template.ts, packages/lib/server-only/field/remove-signed-field-with-token.ts, packages/lib/server-only/field/set-fields-for-template.ts, packages/lib/server-only/field/sign-field-with-token.ts, packages/lib/server-only/recipient/get-recipients-for-template.ts, packages/lib/server-only/recipient/set-recipients-for-template.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/lib/server-only/template/duplicate-template.ts, packages/lib/server-only/template/get-templates.ts, packages/prisma/migrations/20231208090322_remove_template_specific_models/migration.sql, packages/prisma/schema.prisma, packages/ui/primitives/template-flow/add-template-fields.tsx, packages/ui/primitives/template-flow/add-template-placeholder-recipients.tsx
=> refactor: merge template recipient and fields back into default models

apps/marketing/src/app/(marketing)/open/monthly-new-users-chart.tsx, apps/marketing/src/app/(marketing)/open/monthly-total-users-chart.tsx, apps/marketing/src/app/(marketing)/open/tooltip.tsx
---
name: Rename Metrics
---
- Monthly Users and new Users were renamed without monthly to ensure clarity.
- [ x ] I have tested these changes locally and they work as expected.
- [ x ] I have added/updated tests that prove the effectiveness of these changes.
- [ x ] I have updated the documentation to reflect these changes, if applicable.
- [ x ] I have followed the project's coding style guidelines.
- [ x ] I have addressed the code review feedback from the previous submission, if applicable.
-
=> chore: user metrics naming, adopters description

.github/workflows/stale.yml
Issues that have an open pull request and are currently in the review period have been closed due to inactivity before.
Fixed it.
=> chore: update the stale to prevent automatic closure of issues

README.md
I had the committed the changes on the README file for the above issue.I hope my commit resolves the issue.If not,please let me know for any further changes.
=> Docs/change url for cloning (Issue #779)

README.md, apps/marketing/package.json, apps/web/package.json, package-lock.json, railway.toml
- Added `railway.toml` to deploy from `/docker/Dockerfile`
- Added Koyeb as a deploy option
=> feat: updated one-click deploys

package-lock.json, packages/eslint-config/package.json, packages/tailwind-config/package.json
Fixes Dependabot Vulnerabilities listed here, https://github.com/documenso/documenso/security/dependabot
=> chore: fix package vulnerabilities

apps/marketing/src/components/(marketing)/widget.tsx
=> fix: stepsRemaining value of the early adopters plan's input section

.github/ISSUE_TEMPLATE/improvement.yml
Ref #622 
Consolidated the template(removed redundant fields), added appropriate validation.
=> refactor: General Improvement Request Template

apps/web/src/components/(dashboard)/common/command-menu.tsx
When you're in the `/documents` page in the dashboard, if you hover over a draft and a completed document, you'll see different URLs.
At the moment, the shortcut tries to go to the following URL for a completed document `/documents/{doc-id}`. 
However, that's the wrong URL, since the URL for a completed doc is `/sign/{token}` when the user is the recipient, not the one that sent the document for signing.
If it's the document owner & the document is completed, the URL is fine as `/documents/{doc-id}`.
=> fix: fix bug for completed document shortcut

docker/compose.yml
=> fix: docker compose variable

apps/marketing/src/app/(marketing)/open/data.ts
---
name: Add addi to open page
---
=> chore: add adi to open page

packages/email/template-components/template-footer.tsx
---
name: Mail Footer Link tracking
---
=> chore: first small step to tracking growth mechanics

apps/web/src/app/(unauthenticated)/signup/page.tsx, apps/web/src/components/forms/signin.tsx, apps/web/src/components/forms/signup.tsx
This PR links to this issue: #791 
Now users can see a new option to sign up with Google on the signup page.
**Screenshots (Sing In Page):** 
**Screenshots (Sing Up Page):**
=> feat: sign up with Google

apps/marketing/src/components/(marketing)/widget.tsx, apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/components/forms/profile.tsx, apps/web/src/components/forms/signup.tsx, packages/ui/primitives/signature-pad/signature-pad.tsx
=> fix: Added signing pad disable state while submitting form

apps/marketing/src/app/(marketing)/layout.tsx
This Issue https://github.com/documenso/documenso/issues/904
=> fix: add responsive for blog preview mobile view

packages/ui/primitives/document-flow/add-title.tsx, packages/ui/primitives/document-flow/add-title.types.ts
=> fix: empty document titles

apps/web/src/components/(dashboard)/layout/header.tsx, apps/web/src/components/(dashboard)/layout/mobile-navigation.tsx, apps/web/src/components/(dashboard)/layout/profile-dropdown.tsx, apps/web/src/components/(dashboard)/settings/layout/desktop-nav.tsx, apps/web/src/components/(dashboard)/settings/layout/mobile-nav.tsx, apps/web/src/components/(teams)/dialogs/create-team-checkout-dialog.tsx, apps/web/src/components/forms/2fa/authenticator-app.tsx, packages/lib/constants/feature-flags.ts, packages/ui/primitives/sheet.tsx
Add the ability to feature flag the teams feature via UI.
Also added minor UI changes
=> feat: add team feature flag

packages/ui/primitives/command.tsx, packages/ui/primitives/document-flow/add-fields.tsx
=> fix: highlighting issue in recipient selection

apps/web/src/components/forms/2fa/enable-authenticator-app-dialog.tsx, apps/web/src/components/forms/2fa/view-recovery-codes-dialog.tsx, packages/lib/client-only/download-file.ts, packages/lib/client-only/download-pdf.ts
fixes #938 
https://github.com/documenso/documenso/assets/81948346/8bf807ae-41b0-417b-9f55-d96584e71acb
=> feat: ability to download all the 2FA recovery codes

apps/web/src/components/(dashboard)/layout/menu-switcher.tsx
=> fix: put max height in teams section in profile dropdown

apps/marketing/src/components/(marketing)/pricing-table.tsx
hotfix for broken signup links
=> fix: hardcode signup until env issue is fixed

apps/marketing/src/app/(marketing)/singleplayer/client.tsx, apps/web/src/app/(signing)/sign/[token]/page.tsx, apps/web/src/app/(signing)/sign/[token]/provider.tsx, apps/web/src/app/(signing)/sign/[token]/text-field.tsx, packages/lib/server-only/pdf/insert-field-in-pdf.ts, packages/trpc/server/singleplayer-router/helper.ts, packages/trpc/server/singleplayer-router/schema.ts, packages/ui/primitives/document-flow/add-fields.tsx, packages/ui/primitives/document-flow/add-signature.tsx, packages/ui/primitives/document-flow/add-signature.types.ts, packages/ui/primitives/document-flow/add-subject.tsx, packages/ui/primitives/document-flow/single-player-mode-fields.tsx, packages/ui/primitives/template-flow/add-template-fields.tsx
https://github.com/documenso/documenso/assets/55143799/c0f296ce-1e91-4b49-9c19-1bdffbd3163f
=> feat: custom text field

apps/web/src/app/(dashboard)/documents/[id]/document-page-view.tsx, apps/web/src/app/(dashboard)/templates/data-table-templates.tsx, apps/web/src/app/(dashboard)/templates/use-template-dialog.tsx, packages/app-tests/e2e/templates/manage-templates.spec.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/lib/server-only/template/find-templates.ts, packages/prisma/seed/templates.ts, packages/trpc/server/template-router/router.ts, packages/trpc/server/template-router/schema.ts, packages/ui/primitives/document-flow/add-signers.tsx
https://github.com/documenso/documenso/assets/55143799/85a840e3-4fb4-4c02-ba63-b9626f4cea58
=> feat: edit recipients when creating document from template

apps/marketing/content/blog/launch-week-2-day-1.mdx
=> chore: blog day 1

apps/marketing/content/blog/launch-week-2-day-1.mdx
---
---
- Change 1
- Change 2
- ...
- ...
=> chore: typo

apps/web/src/components/forms/v2/signup.tsx, packages/trpc/server/auth-router/router.ts
fixed #981 
`url.length <= 6` >>> `url.length < 6`
also removed debug message from the form component
=> fix: username min length + fixed condition

apps/marketing/src/app/(marketing)/layout.tsx, apps/web/src/app/(dashboard)/settings/profile/claim-profile-alert-dialog.tsx, apps/web/src/components/forms/v2/signup.tsx
**Settings Page:**
**Claim Modal:**
=> chore: update profile claim dialog and modal

README.md
Updated broken link to code of conduct in the Readme
=> chore: updated code of conduct link

apps/web/src/components/forms/v2/signup.tsx, apps/web/src/components/ui/user-profile-skeleton.tsx, apps/web/src/components/ui/user-profile-timur.tsx
=> fix: overflow issue with user name input

apps/web/src/components/forms/2fa/enable-authenticator-app-dialog.tsx, apps/web/src/components/forms/2fa/view-recovery-codes-dialog.tsx
Issue found by guatam in Documenso Discord.
https://discord.com/channels/1132216843537485854/1133420505030987857/1215716399822147664
Bug Loom:
https://www.loom.com/share/b7defde91dfb437580c13c7f166f59ff?sid=cbca746f-174a-44ad-997c-cf3a2eef8380
Fix Loom:
https://www.loom.com/share/8748ac47459247a49ddf7d5379e2a0a0?sid=02977122-c150-44e8-9a19-4c8356c298d7
=> fix: ensure password input is cleared when 2fa enable dialog is closed

apps/marketing/contentlayer.config.ts, apps/marketing/src/app/(marketing)/blog/[post]/page.tsx, apps/marketing/src/app/(marketing)/open/page.tsx, apps/marketing/src/components/(marketing)/CTA.tsx, apps/marketing/src/components/(marketing)/call-to-action.tsx
=> feat: add website cta

packages/lib/server-only/document/seal-document.ts, packages/lib/server-only/document/send-completed-email.ts
This PR sends an email to the document owner once the signing has been completed
=> chore: send email to document owner

.devcontainer/on-create.sh
Updates the `on-create.sh` script to use our `dx` command resolving issues where it couldn't find the docker compose file due to changes that have happened since publishing the Documenso docker image.
Resolves #1026
N/A
N/A
=> fix: update codespaces on create script

apps/web/src/components/forms/public-profile-claim-dialog.tsx
=> fix: username overflow issue

apps/marketing/src/app/(marketing)/layout.tsx, apps/marketing/src/components/(marketing)/pricing-table.tsx
=> feat: add sticky behavior to pricing options container

apps/web/src/components/ui/user-profile-skeleton.tsx
changed the user preview in user-profile-skeleton to lowercase to match ui of other components
---
---
fixed CSS to fix the bug.
#1060
added lowercase to div containing user.url
- Change 1
added tailwind class lowercase to div containing {baseUrl.host}/u/{user.url}  
- ...
- ...
=> fix: user preview to lowercase

packages/trpc/server/auth-router/router.ts
Fixed issue where passkeys do not work on https deployments.
=> fix: passkey login

apps/web/src/app/(dashboard)/admin/users/data-table-users.tsx, apps/web/src/components/(dashboard)/avatar/stack-avatars.tsx, apps/web/src/components/branding/logo.tsx, apps/web/src/components/formatter/template-type.tsx, apps/web/src/components/forms/2fa/view-recovery-codes-dialog.tsx, apps/web/src/components/forms/profile.tsx, apps/web/src/components/ui/background.tsx, apps/web/src/providers/next-theme.tsx
Cleaned up code that was being highlighted in the dev tools
=> fix: linting warnings

apps/marketing/next.config.js, apps/marketing/package.json, apps/marketing/src/app/layout.tsx, apps/web/next.config.js, apps/web/package.json, apps/web/src/app/layout.tsx, package-lock.json
Added support for Axiom web vitals
https://axiom.co/docs/apps/vercel#web-vitals
If this isn't required, please feel free to close the issue.
=> feat: add axiom web vitals

packages/trpc/server/admin-router/router.ts, packages/trpc/server/api-token-router/router.ts, packages/trpc/server/document-router/router.ts, packages/trpc/server/field-router/router.ts, packages/trpc/server/profile-router/router.ts, packages/trpc/server/singleplayer-router/router.ts, packages/trpc/server/template-router/router.ts, packages/trpc/server/webhook-router/router.ts
Increase coverage of error logging in TRPC routes.
=> fix: improve error log coverage

README.md
This PR adds the package to our tech stack
=> chore: add @documenso/pdf-sign to the tech stack

apps/marketing/src/app/(marketing)/layout.tsx
=> feat: update marketing banner

packages/ui/primitives/document-flow/add-settings.tsx, packages/ui/primitives/document-flow/add-signers.tsx
Hide the account reauth option
=> fix: hide account action reauth

apps/web/src/app/(unauthenticated)/articles/signature-disclosure/page.tsx
Description:
This PR updates the dark mode text for this article, https://app.documenso.com/articles/signature-disclosure
=> chore: updated dark mode text

packages/ui/primitives/template-flow/add-template-placeholder-recipients.tsx
This PR fixes the button styling issue
**Before:**
**After:**
=> chore: fix button styling

packages/trpc/server/profile-router/router.ts
fixes the caim name length on the profile claim popup
=> fix: profile claim name length

apps/web/src/app/(dashboard)/templates/[id]/edit-template.tsx, apps/web/src/app/(dashboard)/templates/[id]/template-page-view.tsx, apps/web/src/app/(dashboard)/templates/use-template-dialog.tsx, packages/lib/constants/template.ts, packages/ui/components/recipient/recipient-action-auth-select.tsx, packages/ui/components/recipient/recipient-role-select.tsx, packages/ui/primitives/document-flow/add-signers.tsx, packages/ui/primitives/template-flow/add-template-placeholder-recipients.tsx, packages/ui/primitives/template-flow/add-template-placeholder-recipients.types.ts
Update the template flow to allow for entering recipient placeholder emails and names 
- General refactoring
- Added advanced recipient settings for future usage
=> fix: allow template recipients to be filled

apps/web/src/app/(teams)/t/[teamUrl]/settings/tokens/page.tsx, packages/lib/server-only/public-api/get-all-team-tokens.ts
Make it more intuitive by showing an error message on the team's api token page when a non-owner or a non-admin tries to access it.
=> fix: unauthorized access error api tokens page team

.github/workflows/issue-opened.yml
Description:
This PR updates the triage label for new issues
=> chore: updated triage label

.env.example
change the default sender to sth. nicer
=> chore: change default sender name to match prod

apps/marketing/src/components/(marketing)/share-connect-paid-widget-bento.tsx
Small fix, I noticed on the marketing site
=> fix: Capitalise "Stripe"

apps/marketing/src/components/(marketing)/carousel.tsx
added direct link video to documenso.com
=> chore: add direct link video

apps/web/package.json, package-lock.json
Fix issue with the docker image being built in the CI
=> fix: docker ci

apps/marketing/src/components/(marketing)/header.tsx, apps/marketing/src/components/(marketing)/mobile-navigation.tsx
---
---
- Change 1
- Change 2
- ...
- ...
=> chore: add docs to nav

apps/marketing/content/changelog.mdx
=> chore: changelog-160

apps/web/src/app/(dashboard)/settings/billing/page.tsx, packages/ee/server-only/stripe/get-prices-by-interval.ts
Add platform plan to the billing page.
=> feat: add platform plan pricing

packages/lib/translations/de/common.po, packages/lib/translations/de/web.po
---
---
Some translations in the main signing flow where a little stiff/weirdly worded in german. This PR fixes the main offenders in the signing flow.
- Updated the wording in the german translations
=> chore: reword some german translations to increase clarity

packages/lib/utils/billing.ts
Add billing leeway for enterprise plans.
=> fix: add billing leeway

packages/lib/server-only/document/seal-document.ts, packages/lib/server-only/document/send-document.tsx, packages/lib/server-only/pdf/flatten-form.ts, packages/lib/universal/upload/put-file.ts
https://github.com/user-attachments/assets/e10194ca-212b-40ee-b9a1-85ef54829a40
=> fix: prevent hidden layers from being toggled in pdf viewers

packages/ee/server-only/util/is-document-enterprise.ts, packages/lib/utils/billing.ts
Fetch enterprise billing details dynamically instead of using environment variables.
**Pending testing**
=> feat: make enterprise billing dynamic

packages/ui/components/document/document-visibility-select.tsx, packages/ui/primitives/document-flow/add-settings.tsx
PR created because of this comment https://github.com/documenso/documenso/pull/1521#discussion_r1881895305.
=> fix: move permission check outside the document visibility component

packages/ui/components/field/field-tooltip.tsx
https://github.com/user-attachments/assets/525e6c04-fc03-41a7-8299-2a753e9e9fa6
https://github.com/user-attachments/assets/67f7e592-c5ca-47f4-962c-e4a848522d43
=> fix: fieldtooltip blocking the field click

apps/web/src/app/(teams)/t/[teamUrl]/settings/billing/page.tsx
Currently the text rendered on the team billing page doesn't render properly.
These changes should resolve the issue and provide more translation coverage.
=> fix: billing page formatting

packages/api/v1/implementation.ts, packages/lib/server-only/recipient/get-recipient-by-id-v1-api.ts, packages/lib/server-only/recipient/get-recipient-by-id.ts, packages/trpc/server/field-router/router.ts, packages/trpc/server/recipient-router/router.ts, packages/trpc/server/recipient-router/schema.ts, packages/trpc/server/template-router/router.ts
- Add TRPC API endpoint for getting a recipient by ID
- Minor refactoring
=> feat: add get recipient route

apps/documentation/pages/_app.mdx
Removed unwanted semicolon
Removed semicolon from file _app.mdx .
=> fix: remove unwanted semicolon

packages/ui/primitives/document-flow/field-item.tsx
https://github.com/user-attachments/assets/68ba3dfe-757d-481f-956b-4ce7086ef757
=> fix: make small fields draggable

packages/lib/translations/fr/common.po, packages/lib/translations/fr/marketing.po, packages/lib/translations/fr/web.po
- Added missing translations
- Improved existing translations to make them more natural
=> chore: update French translations

.github/workflows/publish.yml
adds missing 'v' in regex  #1405
=> fix: label stable releases as latest

apps/web/src/app/(dashboard)/templates/[id]/edit/edit-template.tsx, packages/app-tests/e2e/templates-flow/template-settings-step.spec.ts, packages/app-tests/e2e/templates/create-document-from-template.spec.ts, packages/app-tests/e2e/templates/direct-templates.spec.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/lib/server-only/template/find-templates.ts, packages/lib/server-only/template/update-template-settings.ts, packages/prisma/migrations/20241231121013_add_visibility_to_template/migration.sql, packages/prisma/schema.prisma, packages/trpc/server/template-router/schema.ts, packages/ui/primitives/template-flow/add-template-settings.tsx, packages/ui/primitives/template-flow/add-template-settings.types.tsx
- Change 1
- Change 2
- ...
- ...
=> fix: add document visibility to template

packages/lib/server-only/recipient/set-document-recipients.ts, packages/lib/server-only/recipient/update-document-recipients.ts, packages/lib/utils/recipients.ts
Fix issue where you cannot edit a pending document when there is a CCer recipient.
=> fix: pending document edit

apps/documentation/package.json, apps/openpage-api/package.json, apps/web/package.json, package-lock.json, package.json, packages/api/v1/implementation.ts, packages/app-tests/e2e/templates/create-document-from-template.spec.ts, packages/app-tests/package.json, packages/eslint-config/package.json, packages/lib/server-only/2fa/setup-2fa.ts, packages/lib/server-only/field/update-field.ts, packages/lib/types/document-form-values.ts, packages/lib/types/field-meta.ts, packages/prisma/index.ts, packages/prisma/package.json, packages/prisma/schema.prisma, packages/prisma/types/types.d.ts, packages/signing/helpers/update-signing-placeholder.ts, packages/signing/transports/google-cloud-hsm.ts, packages/signing/transports/local-cert.ts, packages/ui/package.json
- Add types for Prisma json
- Bump typescript version (required)
- 2FA
- Normal document flow
=> feat: add prisma json types

packages/trpc/server/field-router/router.ts, packages/trpc/server/recipient-router/router.ts
Add duplicate get field endpoints to make the SDK prettier
=> feat: add get field endpoints

apps/documentation/pages/developers/webhooks.mdx, packages/lib/server-only/document/delete-document.ts, packages/prisma/migrations/20250124135853_add_cancelled_event_webhooks/migration.sql, packages/prisma/schema.prisma
https://github.com/user-attachments/assets/9f2ff975-6688-4150-b4e3-0eb21e2b5503
=> chore: add cancelled webhook event

packages/lib/constants/i18n.ts
Add Polish and Italian languages.
=> feat: add Polish and Italian

package-lock.json, packages/prisma/seed/initial-seed.ts
Add multiple example documents, pending documents, and templates for both admin and example users
- Added seeding of multiple example documents and templates for both example and admin users
=> chore: update local seed data

apps/web/src/app/(signing)/sign/[token]/reject-document-dialog.tsx, apps/web/src/app/embed/rejected.tsx, apps/web/src/app/embed/sign/[[...url]]/client.tsx, apps/web/src/app/embed/sign/[[...url]]/schema.ts, packages/lib/server-only/document/complete-document-with-token.ts
=> feat: allow document rejection in embeds

README.md
---
about:  add https:// to fix the link to the new launch in the README
---
add https:// to fix the link to the new launch in the README
-
- add https:// to the link in the README
Clicked the link in Preview, works.
thank you
=> fix: add https:// to fix the link

apps/documentation/pages/developers/embedding/_meta.json, apps/documentation/pages/developers/embedding/index.mdx, apps/documentation/pages/developers/embedding/web-components.mdx
---
---
The web components version of embedding was missing documentation. I've added it here. Let me know if there's anything that should be changed/updated.
- Added details of the npm package used for web components
- Added detail page for how to use the web component version of embed
=> docs: Add documentation for embedding via web components

apps/web/src/app/(signing)/sign/[token]/form.tsx, apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx, apps/web/src/app/embed/direct/[[...url]]/client.tsx, apps/web/src/app/embed/sign/[[...url]]/client.tsx, package-lock.json, packages/app-tests/e2e/document-flow/stepper-component.spec.ts
=> feat: hide signature ui when theres no signature field

packages/lib/server-only/webhooks/trigger/handler.ts
Fix the invalid request body so the webhooks work again.
=> fix: invalid request body

apps/documentation/pages/developers/public-api/reference.mdx
Update the documentation for https://github.com/documenso/documenso/pull/1615
=> docs: prefill fields

apps/web/src/app/(recipient)/d/[token]/sign-direct-template.tsx, apps/web/src/app/embed/direct/[[...url]]/client.tsx, apps/web/src/app/embed/sign/[[...url]]/client.tsx, packages/lib/server-only/template/create-document-from-direct-template.ts, packages/trpc/server/field-router/router.ts, packages/trpc/server/field-router/schema.ts
Fix optional fields blocking the signature process in embeds
=> fix: optional fields in embeds

packages/ui/primitives/signature-pad/signature-pad.tsx
=> fix: signing field disabled when pointer is out of canvas

package.json
Add the `translate:compile` command to the `d` script.
=> chore: update `d` script in package.json

apps/openpage-api/lib/add-zero-month.ts, apps/openpage-api/lib/growth/get-monthly-completed-document.ts, apps/openpage-api/lib/growth/get-signer-conversion.ts, apps/openpage-api/lib/growth/get-user-monthly-growth.ts, apps/openpage-api/lib/transform-data.ts
- Add zero month at the begining of each metric on the open page
=> fix: zero month addition

packages/ui/components/document/document-global-auth-access-select.tsx, packages/ui/components/document/document-global-auth-action-select.tsx
=> chore: set the default value on the top

apps/remix/app/routes/_unauthenticated+/team.verify.transfer.$token.tsx, packages/trpc/server/document-router/router.ts
=> chore: remove legacy document update route

apps/remix/app/routes/api+/branding.logo.team.$teamId.ts
- Fix issues with branding logo not loading
- Add better logging and error messages
=> fix: branding logos

apps/remix/app/storage/lang-cookie.server.ts
=> fix: make lang cookie httpOnly

packages/lib/server-only/document/duplicate-document-by-id.ts, packages/lib/server-only/webhooks/trigger/trigger-webhook.ts
Fix
- Duplicate document should trigger webhook for document created.
=> fix: trigger webhook for duplicated documents

apps/remix/app/components/tables/documents-table-action-dropdown.tsx
=> chore: update dropdown icons

apps/remix/app/routes/_recipient+/sign.$token+/complete.tsx, packages/ui/components/signing-card.tsx
1. Remove section scroll on completed page
2. Increase the card width a bit to support longer text signatures
=> chore: minor ui fixes

apps/remix/app/components/general/webhook-multiselect-combobox.tsx, packages/ui/lib/use-debounce.ts, packages/ui/primitives/multiselect.tsx
Replaces https://github.com/documenso/documenso/pull/1660 with the same code but targeting our main branch.
=> fix: improve multiselect for webhook triggers

apps/remix/app/routes/_internal+/[__htmltopdf]+/certificate.tsx
Previous powered by display logic was incorrect, likely due to a merge conflict.
=> fix: show powered by logic

apps/remix/app/components/embed/embed-direct-template-client-page.tsx, apps/remix/app/components/embed/embed-document-signing-page.tsx, apps/remix/app/components/embed/multisign/multi-sign-document-list.tsx, apps/remix/app/components/embed/multisign/multi-sign-document-signing-view.tsx, apps/remix/app/routes/embed+/v1+/multisign+/_index.tsx, apps/remix/app/types/embed-multisign-document-schema.ts, packages/lib/client-only/hooks/use-element-bounds.ts, packages/trpc/server/embedding-router/_router.ts, packages/trpc/server/embedding-router/apply-multi-sign-signature.ts, packages/trpc/server/embedding-router/apply-multi-sign-signature.types.ts, packages/trpc/server/embedding-router/get-multi-sign-document.ts, packages/trpc/server/embedding-router/get-multi-sign-document.types.ts, packages/ui/components/field/field.tsx, packages/ui/primitives/alert.tsx
Adds the ability to use a multisign embedding for cases where multiple documents need to be signed in a convenient manner.
=> feat: multisign embedding

packages/ee/server-only/limits/server.ts
---
---
Update documents limit calculation to allow unlimited documents for users who:
1. Have no subscription
2. Have the unlimited documents claim flag
This allows us to give certain users unlimited documents in their personal account as required
=> fix: rework documents limits logic

apps/remix/package.json, apps/remix/server/router.ts, package-lock.json
=> fix: rate limit api endpoints

packages/ui/primitives/document-flow/add-subject.tsx
Fixes a small wording inaccuracy.
No issue, noted when using the product and fixed directly.
- Changed text to remove superfluous word.
- No testing.
=> fix(add-subject): remove superfluous word

apps/remix/app/components/general/document-signing/document-signing-auto-sign.tsx, apps/remix/app/components/general/document-signing/document-signing-checkbox-field.tsx, apps/remix/app/components/general/document-signing/document-signing-radio-field.tsx, packages/lib/constants/autosign.ts, packages/lib/server-only/field/sign-field-with-token.ts
Fix the issue with read-only fields being sign-able by the user.
- Change 1
- Change 2
- ...
- ...
=> fix: sign-able readonly fields

.gitignore
=> chore: update gitginore

.github/PULL_REQUEST_TEMPLATE.md
`.github/PULL_REQUEST_TEMPLATE.md` does not support `name` and `about` frontmatter (https://stackoverflow.com/a/66481758), only files in the `.github/PULL_REQUEST_TEMPLATE` _folder_ do.
- no issue
- Removed the frontmatter as a quick fix, potentially might also move the file to the folder instead (although I could not quickly figure out what the default name of the file should be).
- None
=> fix(github): Remove unsupported frontmatter from PULL_REQUEST_TEMPLATE.md

apps/remix/app/components/general/document-signing/document-signing-checkbox-field.tsx, packages/lib/client-only/hooks/use-element-bounds.ts, packages/lib/server-only/pdf/insert-field-in-pdf.ts, packages/lib/server-only/template/create-document-from-template.ts, packages/lib/types/field-meta.ts, packages/ui/components/field/field.tsx, packages/ui/primitives/document-flow/field-content.tsx, packages/ui/primitives/document-flow/field-item-advanced-settings.tsx, packages/ui/primitives/document-flow/field-item.tsx, packages/ui/primitives/document-flow/field-items-advanced-settings/checkbox-field.tsx
Adds the ability to have checkboxes align horizontally wrapping when they would go off the PDF
=> feat: horizontal checkboxes

packages/lib/constants/date-formats.ts
This pull request adds support for a new date format (`dd.MM.yyyy HH:mm`) in the constants file for date formats. The changes ensure the new format is included in both the list of valid date formats and the date format options available for selection.
=> feat: add european date format

packages/lib/constants/app.ts
Add the ability to change the support email. For the signature disclosure page.
I am making this pull request to address #1812. I have not tested this yet because I was hoping this is just a quick fix. I know little about code so I can attempt to do testing if this is a more complex issue.
=> feat: env for support email

apps/documentation/pages/users/email-domains.mdx, packages/lib/types/subscription.ts
Update the documentation for email domains
=> chore: correct the email domains documentation

apps/remix/app/components/general/template/template-drop-zone-wrapper.tsx, apps/remix/app/routes/_authenticated+/t.$teamUrl+/templates._index.tsx, packages/app-tests/e2e/folders/team-account-folders.spec.ts
https://github.com/user-attachments/assets/117b174c-ed18-41cd-844f-2795b27f973a
=> feat: implement Drag-n-Drop for templates

.github/workflows/translations-upload.yml
Fix checkout action for translation extraction
=> fix: translation extraction github action

packages/lib/server-only/organisation/create-organisation.ts
Always create and assign a Stripe customer to an organisation on creation if billing is enabled.
=> fix: create customer on signup

packages/trpc/server/organisation-router/update-organisation.ts
Tested with dummy data in dev environments.
Freshly created organization, with no metadata in the Stripe test acc.
=> feat: sync organization name with stripe

README.md, SIGNING.md, apps/documentation/pages/developers/contributing/contributing-translations.mdx, apps/documentation/pages/developers/self-hosting/how-to.mdx, docker/testing/compose.yml, render.yaml
Remove old references to `@documenso/web`
=> fix: outdated docs

apps/remix/app/components/dialogs/passkey-create-dialog.tsx, apps/remix/app/components/forms/signin.tsx, apps/remix/app/components/general/document-signing/document-signing-auth-passkey.tsx, apps/remix/app/components/general/document-signing/document-signing-auth-provider.tsx, apps/remix/app/components/tables/settings-security-passkey-table-actions.tsx, apps/remix/app/components/tables/settings-security-passkey-table.tsx, packages/trpc/server/auth-router/create-passkey-authentication-options.ts, packages/trpc/server/auth-router/create-passkey-authentication-options.types.ts, packages/trpc/server/auth-router/create-passkey-registration-options.ts, packages/trpc/server/auth-router/create-passkey-registration-options.types.ts, packages/trpc/server/auth-router/create-passkey-signin-options.ts, packages/trpc/server/auth-router/create-passkey-signin-options.types.ts, packages/trpc/server/auth-router/create-passkey.ts, packages/trpc/server/auth-router/create-passkey.types.ts, packages/trpc/server/auth-router/delete-passkey.ts, packages/trpc/server/auth-router/delete-passkey.types.ts, packages/trpc/server/auth-router/find-passkeys.ts, packages/trpc/server/auth-router/find-passkeys.types.ts, packages/trpc/server/auth-router/router.ts, packages/trpc/server/auth-router/schema.ts, packages/trpc/server/auth-router/update-passkey.ts, packages/trpc/server/auth-router/update-passkey.types.ts
Refactor auth router to follow new conventions and enforce request/response schemas.
=> fix: refactor auth router

AGENTS.md
=> chore: add agents file

packages/lib/server-only/email/get-email-context.ts
Fix issue where selecting the email sender won't correctly send using the selected email.
=> fix: email domain sender logic

apps/remix/app/components/dialogs/admin-user-delete-dialog.tsx, apps/remix/app/components/dialogs/admin-user-disable-dialog.tsx, apps/remix/app/components/dialogs/admin-user-enable-dialog.tsx, apps/remix/app/components/dialogs/admin-user-reset-two-factor-dialog.tsx, apps/remix/app/routes/_authenticated+/admin+/users.$id.tsx, apps/remix/app/routes/_unauthenticated+/organisation.invite.$token.tsx, packages/auth/server/lib/utils/handle-oauth-callback-url.ts, packages/lib/jobs/definitions/emails/send-signing-email.handler.ts, packages/lib/server-only/admin/update-user.ts, packages/lib/server-only/user/get-user-by-id.ts, packages/lib/server-only/user/update-profile.ts, packages/trpc/server/admin-router/get-user.ts, packages/trpc/server/admin-router/get-user.types.ts, packages/trpc/server/admin-router/router.ts, packages/trpc/server/profile-router/router.ts, packages/trpc/server/profile-router/schema.ts
- Gather all admin procedures into admin router
- Limit some additional returns
=> chore: refactor routes

apps/remix/app/components/embed/embed-direct-template-client-page.tsx, apps/remix/app/components/embed/embed-document-signing-page.tsx, apps/remix/app/components/general/document-signing/document-signing-form.tsx, apps/remix/app/components/general/document-signing/document-signing-page-view.tsx
Improves the mobile signing UX making actions available via the floating navbar more obvious.
Also adds an automatic switch to the complete button once all fields have been signed.
=> fix: improve mobile signing ux

packages/ui/primitives/signature-pad/signature-pad.tsx
Fixes #2000 
#2000 
Apply translations to signature pad titles
Tested in local on version 1.2.1
=> fix: signature pad translation

packages/app-tests/e2e/document-flow/stepper-component.spec.ts, packages/app-tests/e2e/organisations/organisation-team-preferences.spec.ts, packages/app-tests/e2e/templates/create-document-from-template.spec.ts, packages/lib/constants/date-formats.ts
Add date formats that were removed in a prior pull request causing issues with certain API requests.
=> fix: add removed date formats

packages/lib/translations/de/web.po, packages/lib/translations/en/web.po, packages/lib/translations/es/web.po, packages/lib/translations/fr/web.po, packages/lib/translations/it/web.po, packages/lib/translations/pl/web.po
Extract translations to be translated
=> chore: extract translations
